Feature/trial events
likecoin/likecoin-api-public pull request #13
Opened 2019-01-24 05:08 UTC by nwingt

2019-01-24 06:19 UTC, nnkken approved these changes

2019-01-24 09:04 UTC, williamchong requested changes

2019-01-24 09:04 UTC, williamchong007 commented on src/routes/civic/index.js
> +      } else if (now > end) {
Use `return` like that api below for easier reading and consistent style?
```
    if (now < start) {
      res.sendStatus(404);
      return;
    }
```

2019-01-24 11:35 UTC, mckingho requested changes

2019-01-24 11:35 UTC, mckingho commented on src/routes/civic/index.js
> +      civicLikerStatus: 'subscribed',
suggest the createObj = {
  currentPeriodStart: now,
  currentType: 'trial',
}
A trigger function will update other details.

2019-01-24 11:35 UTC, mckingho commented
Do we have trial quota?

2019-01-24 13:19 UTC, williamchong007 commented
*Add a `quota` field for each event, which we can set a number higher than the expected users
just in case we got surprised spam

2019-01-25 07:16 UTC, williamchong requested changes

2019-01-25 07:16 UTC, williamchong007 commented on src/routes/civic/index.js
> +      await t.update(trialEventRef, { regCount: regCount + 1 });
`regCount` should be `.get()` inside this transaction

2019-01-25 10:39 UTC, williamchong approved these changes

2019-01-25 10:39 UTC, merged