✨ Add bookmarks and follow api
likecoin/likecoin-api-public pull request #156
Opened 2020-06-15 11:05 UTC by williamchong007

2020-06-24 11:47 UTC, nwingt requested changes

2020-06-24 11:47 UTC, nwingt commented on src/routes/users/bookmarks.js
> +const parse = require('url-parse');
`parse` is a bit confusing, how about `urlParse`?

2020-06-24 11:47 UTC, nwingt commented on src/routes/users/bookmarks.js
> +      res.status(400).send('INVALID_URL');
Better to return status code 409, and something like `BOOKMARK_EXISTS` as error code

2020-06-24 11:47 UTC, nwingt commented on src/routes/users/bookmarks.js
> +        res.status(404).send('URL_NOT_FOUND');
BOOKMARK_NOT_FOUND is better?

2020-06-24 11:47 UTC, nwingt commented on src/routes/users/bookmarks.js
> +        res.status(404).send('URL_NOT_FOUND');
Same as above

2020-06-24 11:47 UTC, nwingt commented on src/routes/users/follow.js
> +
Not need to handle 404?

2020-06-29 08:13 UTC, williamchong007 commented on src/routes/users/follow.js
> +
To mimic the behaviour of liker.land api, `DELETE` endpoint can be used to unfollow a user which was not followed in the db. This is also why I used `.set( , { merge: true )`

2020-06-29 08:38 UTC, nwingt approved these changes

2020-06-29 08:47 UTC, merged