✨ Update notification API
likecoin/likecoin-api-public pull request #185
Opened 2020-08-10 10:06 UTC by nwingt

2020-08-10 15:31 UTC, williamchong requested changes

2020-08-10 15:31 UTC, williamchong commented on src/routes/users/notifications.js
> +      await batch.commit();
Batch has a limit of 250 or 500 write per batch, a range request like this might hit this limit.
Please commit once per 250/500 limit (probably using a counter and `%`) , and rmb to commit the remaining in the end of request

2020-08-11 06:00 UTC, williamchong requested changes

2020-08-11 06:00 UTC, williamchong commented on src/routes/users/notifications.js
> +        // no-op
if limit is a non-numerical value, and it errors here, does it break the checking below with non-numerical true-ful value?
Maybe should split input `limit` and value `Number(limit)` into 2 values

2020-08-11 06:00 UTC, williamchong commented on src/routes/users/notifications.js
> +        res.status(400).send('MISSING_BEFORE');
`INVALID_BEFORE` since invalid values fall into this catch also?

2020-08-11 06:19 UTC, nwingt commented on src/routes/users/notifications.js
> +        // no-op
I don't think there is any truthy value while also non-numerical that return by `Number()`. You said split 2 values, you mean variables or what?

2020-08-11 06:57 UTC, williamchong approved these changes

2020-08-11 06:58 UTC, merged