✨ Split file upload and json api in user register/update
likecoin/likecoin-api-public pull request #226
Opened 2021-03-16 08:51 UTC by WeiJun0827

2021-03-18 14:17 UTC, williamchong requested changes

2021-03-18 14:17 UTC, williamchong commented on src/routes/users/registerLogin.js
> +  return req.is('application/json') === 'application/json';
`req.is` allow wildcard checking, if we are checking exact match `application/json` we might as well just check content-type

2021-03-18 14:17 UTC, williamchong commented on src/routes/users/registerLogin.js
> +      bodyParser.urlencoded({ extended: false })(req, res, () => {
Should check for input param `error` in all callback function, just in case

2021-03-18 14:17 UTC, williamchong commented on src/routes/users/registerLogin.js
> +            console.error(err);
No need to `console.error `since `ValidationError` is handled in error handler

2021-03-18 14:17 UTC, williamchong commented on src/routes/users/registerLogin.js
> +function loadUpdateMiddlewareByContentType(req, res, next) {
What is the different between this and the `loadRegisterMiddlewareByContentType` above?

2021-03-18 14:17 UTC, williamchong commented on src/routes/users/registerLogin.js
> +      if (!isJson(req)) {
Using a more verbose variable `isLegacyReq = !isJson(req)` is prefered

2021-03-18 14:17 UTC, williamchong commented on test/api/user.test.js
> +test.serial('USER: Edit user by Json. Case: success', async (t) => {
```suggestion
test.serial('USER: Edit user by JSON. Case: success', async (t) => {
```

2021-03-19 01:21 UTC, WeiJun0827 commented on src/routes/users/registerLogin.js
> +  return req.is('application/json') === 'application/json';
Would that means we prefer to use `req.get('Content-Type') === 'application/json'` here?

2021-03-19 01:32 UTC, WeiJun0827 commented on src/routes/users/registerLogin.js
> +function loadUpdateMiddlewareByContentType(req, res, next) {
`loadRegisterMiddlewareByContentType` applies `csrfCheck`, `bodyParser.urlencoded`, and `multer.single` functions.
`loadUpdateMiddlewareByContentType` applies `csrf`, `bodyParser.urlencoded`, and `multer.single` functions.
The difference is the csrf functions they refer.

2021-03-22 05:38 UTC, williamchong commented on src/routes/users/registerLogin.js
> +  return req.is('application/json') === 'application/json';
```suggestion
  return !!req.is('application/json');
```

2021-03-31 06:44 UTC, williamchong approved these changes

2021-03-31 06:44 UTC, merged