🔨 Add paymentRedirectWhiteList get/post field
likecoin/likecoin-api-public pull request #242
Opened 2021-05-27 07:50 UTC by WeiJun0827

2021-05-27 07:56 UTC, WeiJun0827 commented on src/routes/users/preferences.js
> +    if (paymentRedirectWhiteList !== undefined) {
Just a minor question, would this be preferred?
```suggestion
    if (paymentRedirectWhiteList) {
```

2021-05-27 08:01 UTC, williamchong commented on src/routes/users/preferences.js
> +    if (paymentRedirectWhiteList !== undefined) {
I think the issue is that the API user might want to just update other fields, say `locale`, without affecting `paymentRedirectWhiteList`. In this case, what would you expect the payload for the following 4 cases would be?
1. Remove everything in `paymentRedirectWhiteList`
2. Remove one entry in `paymentRedirectWhiteList`
3. Add one entry in `paymentRedirectWhiteList`
4. Do not change `paymentRedirectWhiteList`

2021-05-27 08:57 UTC, WeiJun0827 commented on src/routes/users/preferences.js
> +    if (paymentRedirectWhiteList !== undefined) {
May I assume the UI will get the prior settings first? If so, the field may remain previous  `paymentRedirectWhiteList` on UI for the user's further edit. And send the payload with:
1. `"paymentRedirectWhiteList": []`
2. `"paymentRedirectWhiteList": [ ... (one URL removed)]`
3. `"paymentRedirectWhiteList": [ ... (one URL added)]`
4. `"paymentRedirectWhiteList": [ ... (untouched)]`

2021-05-27 09:03 UTC, williamchong commented on src/routes/users/preferences.js
> +    if (paymentRedirectWhiteList !== undefined) {
Since in 1. you assume empty array is delete, I think if `paymentRedirectWhiteList` is |undefined` we should leave it untouched. We should delete it if its null or empty array

2021-05-27 09:28 UTC, WeiJun0827 commented on src/routes/users/preferences.js
> +    if (paymentRedirectWhiteList !== undefined) {
I see, so the `!== undefined` part is necessary for our scenario. But I didn't expect the null case, should I add:
```
if (paymentRedirectWhiteList === null) {
    payload.paymentRedirectWhiteList = [];
}
```
at the beginning of the function right?

2021-05-27 10:20 UTC, williamchong commented on src/routes/users/preferences.js
> +    if (paymentRedirectWhiteList !== undefined) {
hmm i think we should add a special case and treat null as delete

2021-05-27 11:05 UTC, WeiJun0827 commented on src/routes/users/preferences.js
> +    if (paymentRedirectWhiteList !== undefined) {
No problem, code has been updated!

2021-05-27 17:08 UTC, williamchong requested changes

2021-05-27 17:08 UTC, williamchong commented on src/routes/users/preferences.js
> +          if (!isValidHttpUrl(paymentRedirectWhiteList[i])) {
should use `.some()`?

2021-05-27 17:08 UTC, williamchong commented on src/routes/users/preferences.js
> +      } else {
The for loop below loops through `paymentRedirectWhiteList` as an array, should the null case be assigning to some variable, instead of assigning to payload? Also we can skip the else case if we assign to a variable then check it instead

2021-05-27 17:08 UTC, williamchong commented
Please also add some simple test cases

2021-05-28 03:20 UTC, WeiJun0827 commented on src/routes/users/preferences.js
> +          if (!isValidHttpUrl(paymentRedirectWhiteList[i])) {
Cool, I will use .some() instead.
```
      if (paymentRedirectWhiteList.some(x => !isValidHttpUrl(x))) {
        res.status(400).send('INVALID_PAYMENT_REDIRECT_URL');
        return;
      }
```

2021-06-03 12:06 UTC, williamchong requested changes

2021-06-03 12:06 UTC, williamchong commented on test/api/user.test.js
> +  const user = testingUser1;
Testcases that reuse testingUser1 for post/get combo test that returns 200 should all be serial
otherwise potential race condition between cases

2021-06-03 22:15 UTC, WeiJun0827 commented on test/api/user.test.js
> +  const user = testingUser1;
Right... forget to change username at the last second

2021-06-03 22:20 UTC, WeiJun0827 commented on test/api/user.test.js
> +  const user = testingUser1;
I think I would just use the same username `testingUser1` for all post & get cases, to make the code unified.

2021-06-04 15:01 UTC, williamchong requested changes

2021-06-04 15:01 UTC, williamchong commented on test/api/user-preferences.test.js
> +test('USER: Get user preferences. Case: Success', async (t) => {
i think this case already exists in the beginning of this file. We should modify the first test instead of adding a new case  if you want to test for payment redirect url GET.

2021-06-07 03:32 UTC, williamchong approved these changes

2021-06-07 06:05 UTC, williamchong commented
@nwingt please also see if you have any comment

2021-06-07 06:25 UTC, nwingt approved these changes
I am fine with the current implementation but do consider rename whiteList to whitelist for consistency

2021-06-07 09:01 UTC, williamchong commented
Maybe we can serve both version then remove one later, in another PR

2021-06-07 09:01 UTC, merged