Feat/liker
likecoin/likecoin-api-public pull request #303
Opened 2022-07-13 14:24 UTC by Tsai-Hsueh-Kuan

2022-07-13 14:37 UTC, williamchong requested changes

2022-07-13 14:37 UTC, williamchong commented on config/config.js
> +config.API_EXTERNAL_HOSTNAME = 'https://api.rinkeby.like.co';
`API_EXTERNAL_HOSTNAME` can be found from `constant`, please remove

2022-07-13 14:37 UTC, williamchong commented on src/util/api/likernft/metadata.js
>  import { API_EXTERNAL_HOSTNAME } from '../../../constant';
Ref: `API_EXTERNAL_HOSTNAME` can be imported like this

2022-07-13 14:37 UTC, williamchong commented on src/routes/likernft/metadata.js
> +        await delay(5);
I guest 1s delay would do, and we have a function called `sleep` in `util/misc`

2022-07-13 14:37 UTC, williamchong commented on src/util/api/likernft/metadata.js
> +  const ogImageUrl = `https://singlecolorimage.com/get/${randomHex}/512x512`;
Please remove this and use empty `title` as final fall back

2022-07-13 14:37 UTC, williamchong commented on src/util/api/likernft/metadata.js
> +      height: 512,
Please put 512 in the top of this file as ALL_CAP constant

2022-07-13 14:37 UTC, williamchong commented on src/routes/likernft/metadata.js
> +let maskedNFTImage;
Why declare `maskedNFTImage` here, under what case we reuse this across request?

2022-07-13 14:37 UTC, williamchong commented on src/routes/likernft/metadata.js
> +        }
This can be an else case of line 106 instead of putting this here?

2022-07-16 18:45 UTC, williamchong requested changes

2022-07-16 18:45 UTC, williamchong commented on src/util/api/likernft/metadata.js
> +export async function getImage(image, title) {
```suggestion
export async function getFinalNFTImage(image, title) {
```

2022-07-16 18:45 UTC, williamchong commented on src/util/api/likernft/metadata.js
> +  // const imgPath = path.join(__dirname, '../../../assets/iscn.png');
Please remove if not used

2022-07-16 18:45 UTC, williamchong commented on src/util/api/likernft/metadata.js
> +  const randColor = () => `#${Math.floor(Math.random() * 16777215).toString(16).padStart(6, '0').toUpperCase()}`;
Please don't set background color, since background color is a separated field in metadata
Keep the background transparent if possible

2022-07-16 18:45 UTC, williamchong commented on src/util/api/likernft/metadata.js
> +    .toBuffer();
Is the result still a piped stream if `toBuffer()` is called?

2022-07-16 18:45 UTC, williamchong commented on src/util/api/likernft/metadata.js
> +    .toBuffer();
Is the result still a piped stream if toBuffer() is called here?

2022-07-16 18:45 UTC, williamchong commented on src/util/api/likernft/metadata.js
>      .toBuffer();
Is the result still a piped stream if toBuffer() is called with await before returning?

2022-07-16 18:45 UTC, williamchong commented on src/util/api/likernft/metadata.js
> +export async function getImageStream(image, title, color) {
Where is `getImageStream` used?

2022-07-16 18:45 UTC, williamchong commented on src/util/api/likernft/metadata.js
> +    imageBuffer = (await axios.get(image, { responseType: 'arraybuffer' })).data;
Should `responseType` be stream instead of `arraybuffer` ? using `arraybuffer` makes pipe useless since it's blocking

2022-07-18 02:11 UTC, Tsai-Hsueh-Kuan commented on src/util/api/likernft/metadata.js
> +export async function getImageStream(image, title, color) {
this is useless,I removed

2022-07-20 17:12 UTC, williamchong approved these changes

2022-07-20 17:12 UTC, merged