Feature/social graph API
likecoin/likecoin-api-public pull request #308
Opened 2022-07-27 06:52 UTC by lancatlin

+ add `/likernft/collector?creator=` and `/likernft/creator?collector=` API
+ get original response from indexer and aggregate price from firestore
+ order by total value desc

2022-07-27 17:26 UTC, williamchong requested changes

2022-07-27 17:26 UTC, williamchong commented on src/routes/likernft/socialgraph.js
> +    res.status(401).send({ error: 'creator is required' });
This seems to be a `400` error instead of `401`
also we use plaintext error e.g. `MISISNG_CREATOR`

2022-07-27 17:26 UTC, williamchong commented on src/routes/likernft/socialgraph.js
> +    res.status(401).send({ error: 'creator is required' });
This seems to be a `400` error instead of `401`
also we use plaintext error e.g. `MISISNG_CREATOR`

2022-07-27 17:26 UTC, williamchong commented on src/routes/likernft/socialgraph.js
> +  res.send(result);
Prefer `json()` if the result is json

2022-07-27 17:26 UTC, williamchong commented on src/routes/likernft/socialgraph.js
> +  res.send(result);
Prefer `json()` if the result is json

2022-07-27 17:26 UTC, williamchong commented on src/routes/likernft/socialgraph.js
> +  const result = await getCreator(collector);
Please wrap the whole route in `try catch` where in the catch block we call `next(error)`

2022-07-27 17:26 UTC, williamchong commented on src/routes/likernft/socialgraph.js
> +  const result = await getCollector(creator);
Please wrap the whole route in `try catch` where in the catch block we call `next(error)`

2022-07-27 17:26 UTC, williamchong commented on src/util/api/likernft/socialgraph.js
> +    console.log(err.message);
Please use `console.error` for actual error.
Any reason we don't throw this error to let the route handle instead of returning empty?

2022-07-27 17:26 UTC, williamchong commented on src/util/api/likernft/socialgraph.js
> +    return { error: err.message };
Please use `console.error` for actual error.
I think the issue of returning `error` object is that we don't check if the return value contains `error` and throw http 4xx/5xx accordingly
For now I think just throwing `err` is simpler

2022-07-27 17:26 UTC, williamchong commented on src/util/api/likernft/socialgraph.js
> +    value.collections.forEach(
What is the length of `value.collections` are we expecting? depends on the length we might want `getLatestNFTPriceAndInfo` to be blocking or parallel

2022-07-27 17:26 UTC, williamchong commented on src/util/api/likernft/socialgraph.js
> +                console.log(err, iscnPrefix, classId);
What kind of error are we expecting? Also please use `console.error` for actual error

2022-07-27 17:26 UTC, williamchong commented on src/util/api/likernft/socialgraph.js
> +              .then(({ price }) => {
if the NFT is soldout, price might be undefined, we should use `lastSoldPrice` in this case

2022-07-27 17:26 UTC, williamchong commented on src/util/api/likernft/socialgraph.js
> +            getLatestNFTPriceAndInfo(iscnPrefix, classId)
I think one way we can optimize this API is to add a flag in `getLatestNFTPriceAndInfo`. We would want to ignore `getLowerestUnsoldNFT` and just call `likeNFTCollection.doc(iscnPrefix).get()` which is much less expensive to call

2022-07-27 17:26 UTC, williamchong commented on src/util/api/likernft/socialgraph.js
> +          new Promise((resolve) => {
Just push `getLatestNFTPriceAndInfo.then()` which is already a promise, no need to `new Promise`

2022-07-27 17:26 UTC, williamchong commented on src/util/api/likernft/socialgraph.js
> +                });
I think we can have a default estimation of total price according to current pricing table?
(In fact I am not sure if we can skip the firestore part entirely, and just query by lookup table given we never change the price)

2022-07-28 02:17 UTC, lancatlin commented on src/util/api/likernft/socialgraph.js
> +                console.log(err, iscnPrefix, classId);
Some NFT may be issued by user themselves so we cannot find record in firestore

2022-07-28 03:12 UTC, lancatlin commented on src/util/api/likernft/socialgraph.js
> +    value.collections.forEach(
`value.collections` is related to how many works the creator has published. I think it would be less than 100 for normal situation? Because most of collections in different collector may be duplicated, I think doing some cache will help.

2022-08-03 08:09 UTC, closed without merging