✨ Support `transferMultiple`
likecoin/likecoin-api-public pull request #31
Opened 2019-04-04 03:24 UTC by Aludirk

📦 Update `firebase-admin` & `sharp`
✨ Support test on specific file by `yarn test ${test_file}`
✨ Support `transferMultiple` for tx info and tx history with address filter

2019-04-04 04:04 UTC, nwingt commented on src/util/ValidationHelper.js
> +}, filterAddr) {
Prefer using object for options e.g. `options = { filterAddr: '' } `

2019-04-04 06:47 UTC, williamchong007 commented on src/routes/tx/index.js
> +    const filterAddress = req.query.address;
```suggestion
  const { address: filterAddress } = req.query;
```

2019-04-11 11:56 UTC, williamchong requested changes

2019-04-11 11:56 UTC, williamchong007 commented on src/routes/tx/index.js
> +function filterMultipleTxData({
`normalizeMultipleTxData` should be better since without `opt` this does not filter anything

2019-04-11 11:56 UTC, williamchong007 commented on src/routes/tx/index.js
> +}, opt) {
Rename `opt` -> `filter` sounds more verbose

2019-04-11 11:56 UTC, williamchong007 commented on src/routes/tx/index.js
> +        values[0] = new BigNumber(values[0]).plus(new BigNumber(value[index])).toString();
using `Array` for reduce operation is confusing, should either stick with single value or use map

2019-04-11 11:56 UTC, williamchong007 commented on src/routes/tx/index.js
> +      Object.assign(payload, filterMultipleTxData(payload, { address }));
FYI this can also be written in spread 
```const payload = {...payload, ...filterMultipleTxData(payload, { address })}```

2019-04-15 09:42 UTC, williamchong approved these changes

2019-04-15 09:44 UTC, merged