✨ Add transferring NFT endpoint
likecoin/likecoin-api-public pull request #313
Opened 2022-07-29 08:52 UTC by WeiJun0827

2022-07-29 09:49 UTC, williamchong requested changes

2022-07-29 09:49 UTC, williamchong commented on src/util/api/likernft/transfer.js
> +    const { lastUpdateTimestamp: dbTimestamp } = nftDoc.data();
how about `lastUpdateTimestamp: dbTimestamp = 0`

2022-07-29 09:49 UTC, williamchong commented on src/routes/likernft/transfer.js
> +      const { data } = await axios.get(`${COSMOS_LCD_INDEXER_ENDPOINT}/cosmos/tx/v1beta1/txs/${txHash}`);
Would just getting via stargateclient's getTx() be easier? this path does not hit indexer db anyway

2022-07-29 09:49 UTC, williamchong commented on src/routes/likernft/transfer.js
> +      } = data.tx.body.messages[0];
Should we find target event in message or it is always first? what if there does not exists class_id in first message? i.e random message hash

2022-07-29 09:49 UTC, williamchong commented on src/routes/likernft/transfer.js
> +      const { data } = await axios.get(`${COSMOS_LCD_INDEXER_ENDPOINT}/cosmos/tx/v1beta1/txs/${txHash}`);
Also what if tx not found

2022-07-29 09:49 UTC, williamchong commented on src/routes/likernft/transfer.js
> +      });
No response?

2022-07-29 13:58 UTC, WeiJun0827 commented on src/util/api/likernft/transfer.js
> +    const { lastUpdateTimestamp: dbTimestamp } = nftDoc.data();
great!

2022-07-29 14:35 UTC, WeiJun0827 commented on src/routes/likernft/transfer.js
> +      });
Do return `res.json()` if it's successful. Is it OK?

2022-07-29 14:44 UTC, williamchong commented on src/routes/likernft/transfer.js
> +      });
Oh I missed the `res.json()` part, nevermind

2022-07-30 04:22 UTC, williamchong approved these changes

2022-07-30 04:56 UTC, merged