👽  Update parsing & test after redirect fix
likecoin/likecoin-api-public pull request #342
Opened 2022-09-03 14:56 UTC by nwingt

2022-09-06 17:36 UTC, williamchong requested changes

2022-09-06 17:36 UTC, williamchong commented on src/routes/oembed/index.js
> +  // /nft/?class_id=(class_id)
We still need to support `/nft/(nft_class)` and `/(nft_class)` in case the url didn't go through redirect and just hit our oembed api

2022-09-08 04:25 UTC, nwingt commented on src/routes/oembed/index.js
> +  // /nft/?class_id=(class_id)
Ok

2022-09-08 10:04 UTC, williamchong approved these changes

2022-09-13 03:41 UTC, AuroraHuang22 approved these changes

2022-09-13 16:56 UTC, williamchong approved these changes

2022-09-13 16:57 UTC, merged