✨ Support dynamic Liker avatar size
likecoin/likecoin-api-public pull request #382
Opened 2022-10-27 07:31 UTC by WeiJun0827

2022-10-27 10:40 UTC, williamchong requested changes

2022-10-27 10:40 UTC, williamchong commented on src/routes/users/getPublicInfo.js
> +      throw new ValidationError('Invalid size');
I think we can cast the number in range using Math.min and Math.max instead of error

2022-10-27 10:40 UTC, williamchong commented on src/routes/users/getPublicInfo.js
> +        .jpeg();
Use `content-type` header from stream to determine content type, don't hardcode jpeg

2022-10-27 10:40 UTC, williamchong commented on src/routes/users/getPublicInfo.js
> +        .jpeg();
In fact just setting `content-type` in `res` without handling any filetype logic in sharp might already do

2022-10-31 05:41 UTC, williamchong requested changes

2022-10-31 05:41 UTC, williamchong commented on src/util/api/users/getPublicInfo.js
> +  payload.avatar = `https://${API_EXTERNAL_HOSTNAME}/users/id/${id}/avatar`;
Can we add `size` qs with default value here to hint there is a size configurable?
define `const DEFAULT_AVATAR_SIZE = 400` in `constant and
```suggestion
  payload.avatar = `https://${API_EXTERNAL_HOSTNAME}/users/id/${id}/avatar?size=${DEFAULT_AVATAR_SIZE}`;
```

2022-10-31 05:41 UTC, williamchong commented on src/routes/users/getPublicInfo.js
> +    const { size: inputSizeStr = '400' } = req.query;
Please refactor to `constant`

2022-10-31 05:41 UTC, williamchong commented on src/routes/users/getPublicInfo.js
> +      res.sendStatus(404);
Use default avatar in this case?

2022-10-31 06:12 UTC, WeiJun0827 commented on src/routes/users/getPublicInfo.js
> +    const { size: inputSizeStr = '400' } = req.query;
BTW, do we have a preferred `minSize` and `maxSIze` for avatar?

2022-10-31 06:27 UTC, WeiJun0827 commented on src/routes/users/getPublicInfo.js
> +      res.sendStatus(404);
Currently, we had handled those who are Liker but don't provide an avatar in `getUserAvatar(id)`:
https://github.com/likecoin/likecoin-api-public/pull/382/files#diff-bee447251ba2e2147edcd9db72fd0bd3026cc5bb4e9c66f8c3431fc7712adcf2R71-R77

And for those who are not Liker, we display avatars generated by dicebear API in liker.land.

Do we prefer to use the default avatar rather than dicebear avatar for web3 users?

2022-10-31 06:36 UTC, nnkken commented on src/util/api/users/getPublicInfo.js
> +  if (query.docs.length < 0) return null;
`<=`?

2022-10-31 06:36 UTC, nnkken commented on src/routes/users/getPublicInfo.js
> +      res.sendStatus(404);
Usually we prefer exit fast for this kind of `if` branches, i.e. 
```JS
if (!avatar) {
  res.sendStatus(404);
  // may also need a `return`, depending on how likely we will add things after the whole `if` block in the future
}
// normal logic...
```
This keeps the main branch less indented, also prevents having a long block and then an `else` branch which no body remember what's the context

2022-10-31 07:07 UTC, williamchong commented on src/routes/users/getPublicInfo.js
> +    const { size: inputSizeStr = '400' } = req.query;
maxSize... probably 1920?
minSize > 0 is fine

2022-10-31 07:08 UTC, williamchong commented on src/routes/users/getPublicInfo.js
> +      res.sendStatus(404);
Here we only handle likers

2022-10-31 07:58 UTC, WeiJun0827 commented on src/routes/users/getPublicInfo.js
> +      res.sendStatus(404);
I see, will return default avatar for this case.

2022-10-31 08:07 UTC, WeiJun0827 commented on src/routes/users/getPublicInfo.js
> +      res.sendStatus(404);
On second thought, can someone identify whether the given liker doesn't exist or the liker doesn't set an avatar if this API returns the default avatar? Or it doesn't matter, returning the default avatar for both cases is fine?

2022-10-31 08:09 UTC, williamchong commented on src/routes/users/getPublicInfo.js
> +      res.sendStatus(404);
return 404 on id not exists
return default on id exists but no avatar set

2022-10-31 08:55 UTC, nwingt commented on src/routes/users/getPublicInfo.js
> +      res.sendStatus(404);
Maybe return the default for Liker and dicebear API for wallet without Liker ID ?

2022-10-31 10:03 UTC, williamchong approved these changes

2022-10-31 10:04 UTC, merged