✨ Add `GET /user/:wallet/stats` endpoint
likecoin/likecoin-api-public pull request #388
Opened 2022-11-03 15:29 UTC by WeiJun0827

2022-11-03 15:55 UTC, nwingt commented on src/util/api/likernft/user.js
> +  const arrays = [];
```suggestion
  const batches = [];
```

2022-11-03 15:55 UTC, nwingt commented on src/util/api/likernft/user.js
> +    createdCollectorCount,
For consistency 
### A
```suggestion
    collectedNFTClassCount,
    collectedNFTValue,
    createdNFTClassCount,
    createdCollectorCount,
```

### B
```suggestion
    collectedClassCount,
    collectedValue,
    createdClassCount,
    createdCollectorCount,
```

2022-11-03 15:55 UTC, nwingt commented on src/util/api/likernft/user.js
> +    return price ? acc + price * c.count : acc;
I think we can also calculate `collectedCount` (sum of `c.count`) here, which maybe useful in the future 😊

2022-11-06 20:48 UTC, williamchong requested changes

2022-11-06 20:48 UTC, williamchong commented on src/util/api/likernft/user.js
> +  collectedClasses.foreach((c) => {
is `foreach` intentionally or is it `forEach`?

2022-11-07 05:20 UTC, WeiJun0827 commented on src/util/api/likernft/user.js
> +  collectedClasses.foreach((c) => {
It's a typo but somehow it doesn't break the code. Weird...

2022-11-07 06:43 UTC, williamchong approved these changes

2022-11-07 11:08 UTC, merged