👽️ Include `createdTotalSales` in user stats
likecoin/likecoin-api-public pull request #429
Opened 2023-02-13 09:21 UTC by WeiJun0827

2023-02-13 14:09 UTC, williamchong requested changes

2023-02-13 14:09 UTC, williamchong commented on src/util/api/likernft/user.ts
> +  const createdTotalSales = new BigNumber(totalSalesInNanolike).shiftedBy(-9).toNumber();
maybe round to 2dp or integer?

2023-02-14 02:00 UTC, WeiJun0827 commented on src/util/api/likernft/user.ts
> +  const createdTotalSales = new BigNumber(totalSalesInNanolike).shiftedBy(-9).toNumber();
Yeah, can do. I was thinking leaving the decision to front-end to make?

2023-02-14 04:00 UTC, williamchong commented on src/util/api/likernft/user.ts
> +  const createdTotalSales = new BigNumber(totalSalesInNanolike).shiftedBy(-9).toNumber();
you can't expect to send a bignumber with `number`, if you want frontend to make decision it needs to be `string`

2023-02-14 04:07 UTC, WeiJun0827 commented on src/util/api/likernft/user.ts
> +  const createdTotalSales = new BigNumber(totalSalesInNanolike).shiftedBy(-9).toNumber();
I see, I'll just return an integer.

2023-02-14 04:14 UTC, WeiJun0827 commented on src/util/api/likernft/user.ts
> +  const createdTotalSales = new BigNumber(totalSalesInNanolike).shiftedBy(-9).toNumber();
I see, I'll just return an integer.

2023-02-14 06:11 UTC, merged