✨ Marketplace listing supports paying by Stripe
likecoin/likecoin-api-public pull request #432
Opened 2023-02-21 11:29 UTC by WeiJun0827

2023-02-22 09:14 UTC, williamchong requested changes

2023-02-22 09:14 UTC, williamchong commented on src/routes/likernft/fiat/stripe.ts
> +        listingInfo: {},
Prefer to be null if not listing

2023-02-22 09:14 UTC, williamchong commented on src/routes/likernft/fiat/stripe.ts
> +        const targetListing = listingInfo.find((l) => l.nftId === nftId && l.seller === seller);
Just use the `classId/nftId` query instead of using `.find`
https://github.com/likecoin/likecoin-chain/blob/master/proto/likechain/likenft/v1/query.proto#L109

2023-02-22 09:14 UTC, williamchong commented on src/util/api/likernft/fiat/index.ts
> +    if (listingNftId && seller) {
I think we want to set a `isListing` flag as input param that explicity state we want to use listing
The newly added params `nftId` and `seller` both can have meaning outside listing, we may have other use for them later

2023-02-22 09:14 UTC, williamchong commented on src/util/api/likernft/listing.ts
> +  const amount = new BigNumber(priceInLIKE).shiftedBy(9).toFixed(0);
Can we pass the exact amount (string) in nanolike we obtain in API instead? Any non-integer-LIKE might break this API due to precision error

2023-02-22 09:20 UTC, williamchong requested changes

2023-02-22 09:20 UTC, williamchong commented on src/util/api/likernft/listing.ts
> +  if (priceInLIKE < actualNftPrice) throw new ValidationError('LISTING_PRICE_NOT_MATCH');
Should use the original nanolike string in listing for comparison to prevent precision error

2023-02-23 04:30 UTC, WeiJun0827 commented on src/util/api/likernft/fiat/index.ts
> +    if (listingNftId && seller) {
I'll store the `isListing` flag in the DB, so the caller of this function can explicitly get the flag from DB and pass it to this function.

2023-02-24 18:22 UTC, williamchong requested changes

2023-02-24 18:22 UTC, williamchong commented on src/util/api/likernft/listing.ts
> +    .map(formatListingInfo)
Strange to have different return format of `fetchNFTListingInfo` and `fetchNFTListingInfoByNFTId` differ by `formatListingInfo`. Can we not call `formatListingInfo` here and call it where we use `fetchNFTListingInfo`?

2023-02-24 18:22 UTC, williamchong commented on src/util/api/likernft/listing.ts
> +  if (priceInLIKE < actualPriceInLIKE) throw new ValidationError('LISTING_PRICE_NOT_MATCH');
Better do this comparision with `bignumber`

2023-02-27 08:21 UTC, williamchong approved these changes

2023-02-27 09:29 UTC, nnkken commented on src/routes/likernft/fiat/stripe.ts
> +      }
I suggest putting these logics into `then` block, so there would be less distracting `if` branches
```JS
if (isListing) {
  promises.push(
    fetchNFTListingInfoByNFTId(classId, nftId)
      .then((info) => {
        const listingInfo = formatListingInfo(info);
        if (!listingInfo || listingInfo.seller !== seller) throw new ValidationError('LISTING_NOT_FOUND');
        const { price } = listingInfo;
        return price;
      }),
  ); 
} else {
  promises.push(
    getLatestNFTPriceAndInfo(iscnPrefix, classId)
      .then(({ price }) => price),
  );
}
const [{ metadata }, price] = await Promise.all(promises) as any;
```

2023-02-27 09:29 UTC, nnkken commented on src/util/api/likernft/fiat/index.ts
> +  const total = price.plus(LIKER_NFT_FIAT_FEE_USD).toFixed(2, 2); // ROUND_CEIL
Simply use `BigNumber.ROUND_CEIL` directly

2023-02-28 12:12 UTC, WeiJun0827 commented on src/routes/likernft/fiat/stripe.ts
> +      }
Much clearer, great insight, thanks!

2023-02-28 13:07 UTC, nnkken approved these changes

2023-03-01 02:44 UTC, merged