🚸 Self-recover missing NFT sold info in DB
likecoin/likecoin-api-public pull request #444
Opened 2023-03-30 09:39 UTC by WeiJun0827

2023-03-30 09:45 UTC, WeiJun0827 commented on src/util/api/likernft/purchase.ts
> +    granterWallet,
Note that we don't provide `sellerWallet, sellerLIKE, stakeholderWallets, stakeholderLIKEs` which appear in the successful purchase flow. Not sure if it's necessary for now/future.

2023-03-30 09:45 UTC, WeiJun0827 commented on src/util/api/likernft/purchase.ts
> +      return shouldUpdateSoldNFT && retryTimes < 1;
If the flow is acceptable, probably can move the `MAX_NFT_PURCHASE_RETRY_TIMES` to config.js

2023-04-05 17:09 UTC, williamchong requested changes

2023-04-05 17:09 UTC, williamchong commented on src/util/api/likernft/purchase.ts
> +  const price = Number(new BigNumber(event.price).shiftedBy(-9).toFixed(0));
Why can we do `toFixed(0)` here? Price can be non-integer

2023-04-06 05:14 UTC, WeiJun0827 commented on src/util/api/likernft/purchase.ts
> +  const price = Number(new BigNumber(event.price).shiftedBy(-9).toFixed(0));
Since `event.price` includes tx fee (e.g. `8002000000 nanolike`), but the price in FIrestore is an integer. Given the condition of NFT sold by API wallet, the tx price queried from `/event` API should be formatted to an integer after excluding the tx fee?

2023-04-06 07:15 UTC, williamchong commented on src/util/api/likernft/purchase.ts
> +  const price = Number(new BigNumber(event.price).shiftedBy(-9).toFixed(0));
Please add a comment to explain this siutuation

2023-04-06 07:52 UTC, nnkken approved these changes

2023-04-06 08:36 UTC, williamchong approved these changes

2023-04-06 08:36 UTC, merged