✨ Auto-send pending claim W.NFT to wallet with verified email
likecoin/likecoin-api-public pull request #449
Opened 2023-04-20 16:35 UTC by WeiJun0827

2023-04-21 09:45 UTC, williamchong requested changes

2023-04-21 09:45 UTC, williamchong commented on src/util/api/likernft/fiat/stripe.ts
> +    return null;
Should print error that is not 404

2023-04-21 09:45 UTC, williamchong commented on src/util/api/likernft/fiat/stripe.ts
> +    wallet = verifiedWallet || wallet;
if wallet exists, should `isPendingClaim` be unset?

2023-04-21 09:45 UTC, williamchong commented on src/util/api/likernft/fiat/stripe.ts
>    if (isPendingClaim) {
Should send a different email + different frontend UI stating we auto detect its wallet and sent already

2023-04-21 09:45 UTC, williamchong commented on src/util/api/likernft/fiat/stripe.ts
> +        key: LIKER_LAND_GET_WALLET_SECRET,
key should not be in query string, use HTTP header like `Authorization` or `X-LIKERLAND-API-KEY`

2023-04-21 11:13 UTC, WeiJun0827 commented on src/util/api/likernft/fiat/stripe.ts
> +    wallet = verifiedWallet || wallet;
I think we use `dummyWallet` as `wallet` if `isPendingClaim = true`?
https://github.com/WeiJun0827/likecoin-api-public/blob/feature/stripe-auto-reply-email/src/routes/likernft/fiat/stripe.ts#L230-L232

2023-04-21 11:21 UTC, ckxpress commented
綁定 wallet 和 verified email 超級有用，paypal 啊。我還有 400 多本書沒派出去，如果這些人在 Liker Land 有驗證郵箱，我就不用問了。然後，我每週得派 Writing NFT 給 Substack 用戶，也是這種情況

2023-04-21 11:23 UTC, williamchong commented on src/util/api/likernft/fiat/stripe.ts
> +    wallet = verifiedWallet || wallet;
We need to know if we actually found a wallet here or it is still dummy though, we would need to send different email/status to frontend after

2023-04-21 11:25 UTC, williamchong commented
> 綁定 wallet 和 verified email 超級有用，paypal 啊。我還有 400 多本書沒派出去，如果這些人在 Liker Land 有驗證郵箱，我就不用問了。然後，我每週得派 Writing NFT 給 Substack 用戶，也是這種情況

Current design is suitable for WNFT only though, would extra design to allow to you 'deposit' NFT you want to send without leaking email => wallet mapping

2023-04-21 11:47 UTC, ckxpress commented
at least there's a binding first. one step closer.

2023-04-22 10:33 UTC, williamchong requested changes

2023-04-22 10:33 UTC, williamchong commented on src/util/ses.ts
> +        Data: '你的 Writing NFT 已送達',
```suggestion
        Data: '你的 Writing NFT 已送達 | Your Writing NFT has arrived',
```

2023-04-22 10:33 UTC, williamchong commented on src/util/ses.ts
> +          <p>我們發現你的信箱已與地址為 ${wallet} 的錢包完成驗證，已將你所購買的 Writing NFT 發送至該錢包。</p>
```suggestion
          <p>你的信箱先前已與地址為 ${wallet} 的錢包完成驗證，你所購買的 Writing NFT 已發送至該錢包。</p>
```

2023-04-22 10:33 UTC, williamchong commented on src/util/ses.ts
> +          <p>We found that your email has been verified with the wallet address ${wallet}, and the Writing NFT you purchased has been sent to the wallet.</p>
```suggestion
          <p>Your email is previously linked with the wallet address ${wallet}, the Writing NFT you purchased has been sent to the wallet.</p>
```

2023-04-22 10:33 UTC, williamchong commented on config/secret.js
> +config.LIKER_LAND_GET_WALLET_SECRET = '1111111111';
Please put in `config/config` instead of `config/secret`, this file is used for private keys only
We would still inject this variable as secret there though

2023-04-22 10:33 UTC, williamchong commented on src/util/api/likernft/fiat/stripe.ts
> +      params: { email },
Does axios auto run `encodeURIComponent` on params?

2023-04-22 10:33 UTC, williamchong commented on src/util/api/likernft/fiat/stripe.ts
> +        claimState = verifiedWallet ? 'An auto claim' : 'An unclaimed';
```suggestion
        claimState = verifiedWallet ? 'An auto claimed' : 'An unclaimed';
```

2023-04-24 03:00 UTC, WeiJun0827 commented on src/util/api/likernft/fiat/stripe.ts
> +      params: { email },
I processed a pseudo purchase at local, axios seems auto-handled the params for me.

2023-04-24 18:15 UTC, merged