✨ Support auto-claiming flow for Stripe purchase w/o providing wallet
likecoin/likecoin-api-public pull request #454
Opened 2023-04-29 03:35 UTC by WeiJun0827

Drafted the claiming steps for the Chinese part of the letter, and will update the English part if it is finalized.

2023-05-02 14:20 UTC, williamchong requested changes

2023-05-02 14:20 UTC, williamchong commented on src/routes/likernft/fiat/stripe.ts
> +  '/pending-count',
```suggestion
  '/pending/count',
```

2023-05-02 14:20 UTC, williamchong commented on src/routes/likernft/fiat/stripe.ts
> +  '/claim',
```suggestion
  '/pending/claim',
```

2023-05-02 14:20 UTC, williamchong commented on src/util/api/likernft/fiat/stripe.ts
> +    claimToken = uuidv4();
Prefer using random at least 32 bytes converted to hex or base64

2023-05-02 14:20 UTC, williamchong commented on src/util/api/likernft/fiat/stripe.ts
> +  if (!TEST_MODE && !isWalletProvided) {
Why not send in `TEST_MODE` ?

2023-05-02 14:20 UTC, williamchong commented on src/util/api/likernft/fiat/index.ts
> +    status: claimToken ? 'pending' : 'done',
```suggestion
    status: claimToken ? 'pendingClaim' : 'done',
```

2023-05-02 14:20 UTC, williamchong commented on src/routes/likernft/fiat/stripe.ts
> +        .where('status', '==', 'pending')
```suggestion
        .where('status', '==', 'pendingClaim')
```

2023-05-02 14:20 UTC, williamchong commented on src/routes/likernft/fiat/stripe.ts
> +        if (status !== 'pending') throw new ValidationError('ALREADY_CLAIMED_OR_CLAIM_ERROR', 409);
```suggestion
        if (status !== 'pendingClaim') throw new ValidationError('ALREADY_CLAIMED_OR_CLAIM_ERROR', 409);
```

2023-05-02 14:20 UTC, williamchong commented on src/routes/likernft/fiat/stripe.ts
> +        const txRes = await client.sendNFTs(
Should update `status` for the tx to prevent race condition, otherwise during `getLikerNFTPendingClaimSigningClientAndWallet` before `t.update(ref`, it is possible multiple tx can be triggered since `status` is still `pending`
In this case any error should reset status, or update status to error

2023-05-03 05:59 UTC, WeiJun0827 commented on src/util/api/likernft/fiat/stripe.ts
> +  if (!TEST_MODE && !isWalletProvided) {
Because we don't load config/aws.json in `TEST_MODE`?
https://github.com/likecoin/likecoin-api-public/blob/master/src/util/ses.ts#L6

2023-05-08 08:28 UTC, williamchong commented on src/util/api/likernft/fiat/stripe.ts
> +  if (!TEST_MODE && !isWalletProvided) {
Maybe the guard should be inside the functions in `ses.ts` instead of all calling functions

2023-05-08 09:43 UTC, williamchong requested changes

2023-05-08 09:43 UTC, williamchong commented on src/routes/likernft/fiat/stripe.ts
> +        ({ classId, nftId } = doc.data());
We can return `{ classId, nftId }` in this transaction instead of using `let`

2023-05-08 09:43 UTC, williamchong commented on src/routes/likernft/fiat/stripe.ts
> +          throw new ValidationError('NFT_CLAIM_ALREADY_HANDLED', 409);
Should fire pubsub (generally anything with side effect) outside of transaction, since transaction might be re-run if the `get` data is changed

2023-05-08 09:43 UTC, williamchong commented on src/routes/likernft/fiat/stripe.ts
> +        );
Should we use `sendTransactionWithSequence` here? possible sequence race condition

2023-05-08 09:43 UTC, williamchong commented on src/routes/likernft/fiat/stripe.ts
> +      if (code) throw new ValidationError(`TX_${txHash}_FAILED_WITH_CODE_${code}`);
Is this a `LikerNFTFiatClaimError` too? Should handle like above

2023-05-08 09:43 UTC, williamchong commented on src/util/api/likernft/fiat/index.ts
> +import uuidv4 from 'uuid/v4';
Can remove if we are not using this now

2023-05-08 12:08 UTC, WeiJun0827 commented on src/routes/likernft/fiat/stripe.ts
> +          throw new ValidationError('NFT_CLAIM_ALREADY_HANDLED', 409);
Will skip this pubsub and let the pubsub with `logType: 'LikerNFTFiatClaimError'` in catch scope handle.

2023-05-08 12:16 UTC, WeiJun0827 commented on src/routes/likernft/fiat/stripe.ts
> +          throw new ValidationError('NFT_CLAIM_ALREADY_HANDLED', 409);
Oh I see, that's the mechanism of Firestore transaction. Thanks!

2023-05-08 12:19 UTC, WeiJun0827 commented on src/routes/likernft/fiat/stripe.ts
> +          throw new ValidationError('NFT_CLAIM_ALREADY_HANDLED', 409);
By the way, is it necessary to add a log here? I copied the code from `processFiatNFTPurchase()`, but not sure if it's OK to just return a `409` without additional log-out.

2023-05-08 13:39 UTC, williamchong commented on src/routes/likernft/fiat/stripe.ts
> +          throw new ValidationError('NFT_CLAIM_ALREADY_HANDLED', 409);
What do you mean by log-out?

2023-05-08 16:57 UTC, WeiJun0827 commented on src/routes/likernft/fiat/stripe.ts
> +          throw new ValidationError('NFT_CLAIM_ALREADY_HANDLED', 409);
Like `console.log` and pubsub here?

2023-05-08 19:26 UTC, williamchong commented on src/routes/likernft/fiat/stripe.ts
> +          throw new ValidationError('NFT_CLAIM_ALREADY_HANDLED', 409);
Good to have consistent logging for all fiat NFT purchase error, better keep the logs
but seems like a `console.error` than `console.log` to me

2023-05-09 17:13 UTC, williamchong approved these changes
Missing english email before merge

2023-05-12 07:36 UTC, merged