✨ Support purchasing multiple W.NFT in a batch
likecoin/likecoin-api-public pull request #460
Opened 2023-05-17 08:43 UTC by WeiJun0827

I think the simplest way of the E2E test is host rinkeby.liker.land and API server locally and hardcode [postNFTPurchase()](https://github.com/likecoin/liker-land/blob/master/src/util/api/index.js#L233)'s `class_id` with an array.

2023-05-18 14:56 UTC, williamchong requested changes

2023-05-18 14:56 UTC, williamchong commented on src/util/NFTValidationError.ts
> +    nftId = '',
Should we support custom data payload in `ValidationError`, instead of making `NFTValidationError`?

2023-05-18 14:56 UTC, williamchong commented on src/routes/likernft/purchase.ts
> +        purchaseInfoList: purchaseInfoList.map((info) => ({
```suggestion
        purchased: purchaseInfoList.map((info) => ({
```

2023-05-18 14:56 UTC, williamchong commented on src/util/api/likernft/purchase.ts
> +        && err.nftId
Is it possible that multiple nfts disappeared, would a failed transaction contains info of all these nfts (instead of just the first one), and can we try all of them together here?

2023-05-18 14:56 UTC, williamchong commented on src/util/api/likernft/purchase.ts
> +        resetLockedPurchaseDocs({
Does firestore transaction has a limitation of number of documents locked? Please guard nft length in API for the limit

2023-05-18 14:56 UTC, williamchong commented on src/util/api/likernft/purchase.ts
> +      await Promise.all(purchaseInfoList.map((info) => updateDocsForSuccessPurchase(t, {
I don't think we should use `Promise.all` inside transaction since ordering here can be undefined, prefer awaiting 1 by 1

2023-05-18 14:56 UTC, williamchong commented on src/util/api/likernft/purchase.ts
> +    )))
I don't think we should use `Promise.all` inside transaction since ordering here can be undefined, prefer awaiting 1 by 1

2023-05-18 15:33 UTC, WeiJun0827 commented on src/util/api/likernft/purchase.ts
> +        && err.nftId
Should test if the blockchain could detect multiple ownership errors from the msg array and return feedback in `rawLog`.

2023-05-19 09:50 UTC, WeiJun0827 commented on src/util/api/likernft/purchase.ts
> +      await Promise.all(purchaseInfoList.map((info) => updateDocsForSuccessPurchase(t, {
Wonder what side effects would happen if we update docs concurrently with `Promise.all` here?

2023-05-19 10:02 UTC, WeiJun0827 commented on src/util/api/likernft/purchase.ts
> +        resetLockedPurchaseDocs({
The doc says `Each transaction or batch of writes can write to a maximum of 500 documents.`. Consider that `updateDocsForSuccessPurchase` will update 3 docs(ISCN, class, NFT) and create one doc(txHash), 500 / 4 = 125. How about setting the limitation of the maximum class number to 100 in a single request?

2023-05-19 10:03 UTC, williamchong commented on src/util/api/likernft/purchase.ts
> +      await Promise.all(purchaseInfoList.map((info) => updateDocsForSuccessPurchase(t, {
Actually i don't know, but firestore transaction requires all get() happen before update(), so if we dont have this guaranteed now then you might have to rewrite this part

2023-05-19 10:27 UTC, WeiJun0827 commented on src/util/api/likernft/purchase.ts
> +      await Promise.all(purchaseInfoList.map((info) => updateDocsForSuccessPurchase(t, {
I see, may keep it sequentially for now.

2023-05-19 10:29 UTC, williamchong commented on src/util/api/likernft/purchase.ts
> +        resetLockedPurchaseDocs({
Yes that would work

2023-05-19 10:30 UTC, williamchong commented on src/util/api/likernft/purchase.ts
> +      await Promise.all(purchaseInfoList.map((info) => updateDocsForSuccessPurchase(t, {
Note that it is all get() before any update() so if you call get then update in a function for each nft class, we might have to refactor and split the function

2023-05-19 13:18 UTC, WeiJun0827 commented on src/util/api/likernft/purchase.ts
> +      await Promise.all(purchaseInfoList.map((info) => updateDocsForSuccessPurchase(t, {
I see, so awaiting 1 by 1 means reading all necessary docs in a `Promise.all`, then updating docs later?
In that case, we would have the process like this:
- a `Promise.all` for batch reading starts
  - first async `t.get` finished
  - ...
  - last async `t.get` finished
- the `Promise.all` completed
- sync processing data for multiple docs
- sync assign `t.update` for all docs
- async  `t.commit` under the `db.runTransaction` triggered 


But what's the difference between the above 1 by 1 case and the original code? Here's the pseudo-process of original code in my mind:
- a `Promise.all` for batch reading and labeling what to write starts
  - all async `getAndUpdate` launched
    - async `t.get` finished
    - sync processing data
    - sync assign `t.update`
  - first `readAndWriteFunc` completed
  - ...
  - last `readAndWriteFunc` completed 
- the `Promise.all` completed
- async `t.commit` under the `db.runTransaction` triggered 

Since the actual update action happens at the last line of both the above process at once. Would we keep the `t.get` and `t.update` in the same function to make the code more structured?

Here's an example of using `Promise.all` to handle a `getAndUpdate`:
https://stackoverflow.com/a/48310739/7978205

2023-05-19 13:29 UTC, williamchong commented on src/util/api/likernft/purchase.ts
> +      await Promise.all(purchaseInfoList.map((info) => updateDocsForSuccessPurchase(t, {
`Promise.all` sounds like a bad idea overall in transaction, but if it is only for `get()`s and if we guarantee the order of write operation, I think we can use it for better performance (as long as it works in firestore)

> a Promise.all for batch reading starts
> first async t.get finished
> ...
> last async t.get finished
> the Promise.all completed
> sync processing data for multiple docs
> sync assign t.update for all docs
> async t.commit under the db.runTransaction triggered
so I think what you describe is what we want.
Do any function we are calling in `Promise.all()` involves a `get()` and `update()` inside a same function?

2023-05-19 13:31 UTC, williamchong commented on src/util/api/likernft/purchase.ts
> +      await Promise.all(purchaseInfoList.map((info) => updateDocsForSuccessPurchase(t, {
> But what's the difference between the above 1 by 1 case and the original code? Here's the pseudo-process of original code in my mind:

Let say there is `[A, B]` in `Promise.all`, and A and B both contains `get()` and `update()`
Do we have any guarantee (code-wise) that `B.get()` will always finish before `A.update()` is called?
If not it is problematic

2023-05-19 13:37 UTC, WeiJun0827 commented on src/util/api/likernft/purchase.ts
> +      await Promise.all(purchaseInfoList.map((info) => updateDocsForSuccessPurchase(t, {
Since the docs to be updated are independent of each other for different classes, is the order of write operation critical here?

2023-05-19 13:42 UTC, williamchong commented on src/util/api/likernft/purchase.ts
> +      await Promise.all(purchaseInfoList.map((info) => updateDocsForSuccessPurchase(t, {
https://firebase.google.com/docs/firestore/manage-data/transactions?hl=zh-tw#transactions
Read must come before write in a same transaction

2023-05-19 14:18 UTC, WeiJun0827 commented on src/util/api/likernft/purchase.ts
> +      await Promise.all(purchaseInfoList.map((info) => updateDocsForSuccessPurchase(t, {
I think the write action is done at the line `this.commit()` inside the `db.runTransaction()` but not the line `t.update()`? The `t.update` is just labeling the doc needs to be updated later. If the call stack has reached the `db.runTransaction()` then all `t.get()` should already be finished.
I tried this snippet and it seems OK:
```
async function readAndWrite(id, t) {
  const ref = collection.doc(id);
  const doc = await t.get(ref);
  const { name } = doc.data();
  t.update(ref, { greeting: `Hello, ${name}` });
}

async function run() {
  const ids = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'];
  await db.runTransaction((t) => Promise.all(ids.map((id) => t.create(collection.doc(id), { name: id }))));
  console.log('Documents created.');
  await db.runTransaction((t) => Promise.all(ids.map((id) => readAndWrite(id, t))));
  console.log('Read and write done.');
}

run();
```

2023-05-19 14:26 UTC, WeiJun0827 commented on src/util/api/likernft/purchase.ts
> +      await Promise.all(purchaseInfoList.map((info) => updateDocsForSuccessPurchase(t, {
Seems fail if I add this part in `readAndWrite`
```
const randonSleep = Math.random() >= 0.5;
  if (randonSleep) {
    await new Promise(resolve => setTimeout(resolve, 5000));
  }
```

2023-06-02 03:23 UTC, WeiJun0827 commented on src/util/api/likernft/purchase.ts
> +        && err.nftId
Seems we can only get one error a time.
Tested [this case](https://node.testnet.like.co/cosmos/tx/v1beta1/txs/B3616FB1C4045957E7FCE952A9506A14187B6B5BBCDDD2D21E7B9C338A2CBE9D).
Where both NFTs are sold in [previous purchase](https://node.testnet.like.co/cosmos/tx/v1beta1/txs/0CBA7D8371EF280CA067D598829D59E1CC618F6B8B7B5C54D053CA45659EF95C), but we can only see one unauthorized error in `raw_log`. 
I guess the chain throws an error as soon as the ownership mismatch is detected and doesn't check the other possible error.

2023-06-03 17:03 UTC, williamchong commented
One quick question before review: Can indexer parse this kind of multiple purchase events in one tx?

2023-06-04 08:44 UTC, WeiJun0827 commented
> One quick question before review: Can indexer parse this kind of multiple purchase events in one tx?

https://node.testnet.like.co/cosmos/tx/v1beta1/txs/0CBA7D8371EF280CA067D598829D59E1CC618F6B8B7B5C54D053CA45659EF95C
Seems it works OK with `nft_event`, but we have some problems with `nft_income` since the parsing logic doesn't expect multiple purchases for now. Should further rewrite paring logic.

<img width="1501" alt="截圖 2023-06-04 下午1 40 58" src="https://github.com/likecoin/likecoin-api-public/assets/33746295/7412be7a-72cb-4cb6-bfaf-80f7176e767d">
<img width="1740" alt="截圖 2023-06-04 下午4 40 59" src="https://github.com/likecoin/likecoin-api-public/assets/33746295/e8675c42-90d8-4afb-aea9-974fb4dea935">

2023-06-05 10:24 UTC, williamchong reviewed
Please also update indexer's extractor, and likerland's memo display logic to support multiple purchase

2023-06-05 10:24 UTC, williamchong commented on src/middleware/likernft.ts
> +    if (classIds.length > 100) throw new ValidationError('CLASS_NUMBER_EXCESS_100', 422);
Please name the number 100 with a const

2023-06-05 10:24 UTC, williamchong commented on src/util/api/likernft/purchase.ts
> +    : '(multiple purchase)';
```suggestion
    : '(multiple purchases)';
```

2023-06-05 11:09 UTC, WeiJun0827 commented on src/middleware/likernft.ts
> +    if (classIds.length > 100) throw new ValidationError('CLASS_NUMBER_EXCESS_100', 422);
Moved to config.js, is it OK?

2023-06-13 14:35 UTC, williamchong approved these changes

2023-06-23 02:35 UTC, merged