🥅 Guard listing NFT has been sent case
likecoin/likecoin-api-public pull request #462
Opened 2023-05-18 16:05 UTC by WeiJun0827

2023-05-18 19:28 UTC, williamchong requested changes

2023-05-18 19:28 UTC, williamchong commented on src/util/api/likernft/listing.ts
> +    axios.get(`${COSMOS_LCD_INDEXER_ENDPOINT}/likechain/likenft/v1/owner?class_id=${classId}`),
I think there is an API that can query the owner of a class id + nft id pair without getting all owners

2023-05-19 05:16 UTC, WeiJun0827 commented on src/util/api/likernft/listing.ts
> +    axios.get(`${COSMOS_LCD_INDEXER_ENDPOINT}/likechain/likenft/v1/owner?class_id=${classId}`),
Is it from [chain API](https://github.com/likecoin/likecoin-chain/blob/master/proto/likechain/likenft/v1/query.proto) or [indexer API](https://github.com/likecoin/likecoin-chain-tx-indexer/blob/master/rest/router.go)?

2023-05-19 08:19 UTC, williamchong commented on src/util/api/likernft/listing.ts
> +    axios.get(`${COSMOS_LCD_INDEXER_ENDPOINT}/likechain/likenft/v1/owner?class_id=${classId}`),
from x/nft chain module
https://github.com/likecoin/likecoin-chain/blob/v3.1.1/backport/cosmos-sdk/v0.46.0-rc1/proto/cosmos/nft/v1beta1/query.proto#L19

2023-05-19 09:10 UTC, WeiJun0827 commented on src/util/api/likernft/listing.ts
> +    axios.get(`${COSMOS_LCD_INDEXER_ENDPOINT}/likechain/likenft/v1/owner?class_id=${classId}`),
updated, thanks!

2023-05-19 09:16 UTC, williamchong approved these changes

2023-05-19 09:16 UTC, merged