👽 Pass claim token to success URL for Stripe sesssion
likecoin/likecoin-api-public pull request #468
Opened 2023-06-05 19:30 UTC by nwingt

Requires likecoin/liker-land#1115

2023-06-05 19:36 UTC, williamchong requested changes

2023-06-05 19:36 UTC, williamchong commented on src/routes/likernft/fiat/stripe.ts
> +          claimToken,
Prefer store it in firestore instead of db
Also we should only set claim token when a wallet is not set on purchase
Also we would need to void this token if a wallet is found with an email (actually should we keep this email auto claim behavior in the new flow?)

2023-06-08 08:49 UTC, williamchong approved these changes

2023-06-08 08:49 UTC, williamchong commented on src/util/api/likernft/fiat/stripe.ts
> +    claimToken = docData.claimToken;
Not sure if we need to check if `docData.claimToken` exists, need to throw an error maybe

2023-06-08 10:10 UTC, nwingt commented on src/util/api/likernft/fiat/stripe.ts
> +    claimToken = docData.claimToken;
Added guard

2023-06-08 20:00 UTC, williamchong approved these changes

2023-06-15 11:29 UTC, merged