💬 Use NFT Book name as link text
likecoin/likecoin-api-public pull request #481
Opened 2023-06-26 09:17 UTC by WeiJun0827

2023-06-26 09:34 UTC, williamchong requested changes

2023-06-26 09:34 UTC, williamchong commented on src/util/api/likernft/book/index.ts
> +      iscnPrefix,
Please edit https://github.com/likecoin/likecoin-api-public/blob/e8e1787114327cc25116ee8cd90cc192b44dd1fc/src/routes/likernft/book/purchase.ts#L65
to make the metadata field consistent with wnft

2023-06-28 17:26 UTC, williamchong requested changes
<img width="617" alt="image" src="https://github.com/likecoin/likecoin-api-public/assets/6198816/75e8a114-4e21-4dfe-ba4e-882bd1bbd04b">
I get undefined name when buying [this](https://rinkeby.liker.land/en/nft/class/likenft1ggkczh9pvsa45f0f2qterymhf6w5y7c2m9v5tmchrn72gzghudtstx4yg2)

2023-06-29 09:24 UTC, williamchong requested changes

2023-06-29 09:24 UTC, williamchong commented on src/util/api/likernft/book/index.ts
> +      getNFTClassDataById(classId),
Please catch error from `getNFTClassDataById` since we don't want it to stop `stripe.paymentIntents.capture` from running

2023-06-29 09:36 UTC, WeiJun0827 commented on src/util/api/likernft/book/index.ts
> +      getNFTClassDataById(classId),
I see, updated

2023-06-29 11:30 UTC, williamchong commented on src/util/ses.ts
> +          <p>Congratulation. A reader has bought your NFT book.</p>
Should this be ` A reader has claim`? Also if `message` exists should we show `message`?

2023-06-29 13:38 UTC, merged