✨ Support purchase multiple wNFT by Stripe
likecoin/likecoin-api-public pull request #521
Opened 2023-09-11 13:13 UTC by WeiJun0827

2023-09-12 01:24 UTC, williamchong requested changes
Need to also handle `processFiatNFTPurchase`

2023-09-12 01:24 UTC, williamchong commented on src/util/api/likernft/index.ts
> -export async function getISCNPrefixByClassIdFromChain(classId) {
Why remove from chain functions?

2023-09-12 01:24 UTC, williamchong commented on src/routes/likernft/fiat/stripe.ts
> +        collects, memo, email,
Please name it `collectInfoList` or `collectNftInfoList` or similar names

2023-09-12 01:24 UTC, williamchong commented on src/util/api/likernft/fiat/stripe.ts
> +  nftId = '',
Is nftId a required param here?

2023-09-12 02:11 UTC, WeiJun0827 commented on src/util/api/likernft/index.ts
> -export async function getISCNPrefixByClassIdFromChain(classId) {
No function is using it, can still keep it

2023-09-12 02:13 UTC, WeiJun0827 commented on src/util/api/likernft/fiat/stripe.ts
> +  nftId = '',
It's optional, only for listing class

2023-09-12 21:30 UTC, williamchong approved these changes

2023-09-12 21:30 UTC, williamchong commented on src/routes/likernft/fiat/stripe.ts
> +      });
Interesting and smart way to populate stripe metadata

2023-09-12 21:30 UTC, williamchong commented on src/routes/likernft/fiat/stripe.ts
>          line_items: [
Actually we can list each nft as a single line item, but that would make price calculation very hard in LIKE case

2023-09-13 02:40 UTC, WeiJun0827 commented on src/routes/likernft/fiat/stripe.ts
>          line_items: [
Or should we split the `LIKER_NFT_FIAT_FEE_USD` as an additional line item?

2023-09-13 05:18 UTC, williamchong approved these changes

2023-09-15 08:31 UTC, williamchong approved these changes

2023-09-15 08:31 UTC, merged