👔 Change wNFT base currency to USD
likecoin/likecoin-api-public pull request #522
Opened 2023-09-18 08:28 UTC by WeiJun0827

2023-09-19 23:15 UTC, williamchong commented on src/util/api/likernft/fiat/stripe.ts
> +      unit_amount: Number(new BigNumber(txFee).shiftedBy(2).toFixed(0)),
Should set round up?

2023-09-19 23:15 UTC, williamchong commented on src/routes/likernft/purchase.ts
> +        const gasFee = 0;
Please add comment to explain hardcode

2023-09-19 23:15 UTC, williamchong commented on src/util/api/likernft/fiat/index.ts
> +    .reduce((acc, { price }) => acc.plus(price), new BigNumber(0)).dividedBy(rate).toFixed(0));
Please round up

2023-09-20 03:00 UTC, WeiJun0827 commented on src/util/api/likernft/fiat/stripe.ts
> +      unit_amount: Number(new BigNumber(txFee).shiftedBy(2).toFixed(0)),
hmmm `txFee` is already a round-up value?

2023-09-20 10:03 UTC, williamchong commented on src/util/api/likernft/fiat/stripe.ts
> +      unit_amount: Number(new BigNumber(txFee).shiftedBy(2).toFixed(0)),
if we are calling `toFixed(0)` anyway might as well just define round up mode

2023-09-25 17:15 UTC, williamchong commented on src/util/api/likernft/purchase.ts
> +  if (totalLIKEPrice && totalLIKEPrice > grantedAmount) {
Can we leave some buffer when checking/report price? We should report price which over estimate LIKE price, then check the price needed here with actual LIKE price
This is to avoid small changes in LIKE price would make the whole tx fail

2023-09-25 17:15 UTC, williamchong commented on src/util/api/likernft/purchase.ts
> +      .catch(() => cachedPrice || LIKER_NFT_FIAT_MIN_RATIO);
We can use async await here without .then and .catch?

2023-09-26 01:43 UTC, WeiJun0827 commented on src/util/api/likernft/purchase.ts
> +  if (totalLIKEPrice && totalLIKEPrice > grantedAmount) {
Is it OK to add the buffer in the labeled LIKE price & granted amount, then deduct the actual LIKE price later?
(See commit https://github.com/likecoin/likecoin-api-public/pull/522/commits/797fd55d09edf1514f962a85ce6eb2cd42b1f314)

Currently, if an NFT of $1 USD is worth $800 LIKE, the shown LIKE price will be $880 LIKE, and request a grant of $880 LIKE. So either LIKE price goes up or down less than 10%, the tx still success, and the LIKE price won't be underestimated if LIKE price goes up. (if we instead use the actual price of $800 LIKE to request a grant then check with buffer later)

2023-09-26 04:16 UTC, williamchong commented on src/util/api/likernft/purchase.ts
> +  if (totalLIKEPrice && totalLIKEPrice > grantedAmount) {
yes current one would be fine

2023-09-26 16:00 UTC, williamchong requested changes

2023-09-26 16:00 UTC, williamchong commented on src/util/api/likernft/purchase.ts
> +    if (shouldDeductStripeTxFee) {
Can we handle stripe fee in `processFiatNFTPurchase` or `processStripeFiatNFTPurchase` ? Since this is totally a stripe or fiat only thing

2023-09-27 01:59 UTC, WeiJun0827 commented on src/util/api/likernft/purchase.ts
> +    if (shouldDeductStripeTxFee) {
Yes, that would be better. But how could we deduct the tx fee before knowing the NFT price? Since the price is fetched inside of `processNFTPurchase`.

2023-09-27 06:35 UTC, williamchong commented on src/util/api/likernft/purchase.ts
> +  txFeeReducer = (p: BigNumber) => p,
Confusing name, the thing being reduce is revenue/profit not txFee, how about priceModifier or sth like that?

2023-09-27 06:35 UTC, williamchong commented on src/util/api/likernft/purchase.ts
> +    const reducedFiatPrice = txFeeReducer(new BigNumber(info.price));
better check txFeeReducer is defined and is a function

2023-09-27 09:17 UTC, williamchong approved these changes

2023-09-28 19:10 UTC, williamchong approved these changes

2023-09-29 04:26 UTC, merged