[TAS-488] ✨ Provide discount if pay by LIKE
likecoin/likecoin-api-public pull request #530
Opened 2023-10-03 07:56 UTC by WeiJun0827

2023-10-03 07:57 UTC, nwingt commented on config/config.js
> +config.LIKER_NFT_PAY_BY_LIKE_PRICE_OFF = 0.4;
```suggestion
config.LIKER_NFT_LIKE_PRICE_DISCOUNT_IN_USD = 0.4;
```

2023-10-03 09:23 UTC, nwingt commented on src/routes/likernft/purchase.ts
> +        .multipliedBy(1 - LIKER_NFT_LIKE_PRICE_DISCOUNT_RATIO);
can we refactor this function to util and reuse in `calculatePayment()`

2023-10-03 09:23 UTC, nwingt commented on src/util/api/likernft/fiat/index.ts
> +    .toFixed(0, BigNumber.ROUND_UP));
How about?
```js
const priceReducer = (acc, { price }) => {
  const discountedPrice = new BigNumber(price)
    .minus(LIKER_NFT_TX_FEE_DISCOUNT_IN_USD)
    .multipliedBy(1 - LIKER_NFT_LIKE_PRICE_DISCOUNT_RATIO);
  return discountedPrice.isLessThanOrEqualTo(0)
    ? acc
    : acc.plus(discountedPrice);
};
const priceReducerWithoutDiscount = (acc, { price }) => acc.plus(price);

const calculateTotalLIKEPrice = (reducer) => Number(
  purchaseInfoList
    .reduce(, new BigNumber(0))
    .dividedBy(rate)
    .multipliedBy(1 + buffer)
    .toFixed(0, BigNumber.ROUND_UP)
);

const totalLIKEPrice = calculateTotalLIKEPrice(priceReducer);
const totalLIKEPriceNoDiscount = calculateTotalLIKEPrice(priceReducerWithoutDiscount);
```

2023-10-03 11:14 UTC, WeiJun0827 commented on src/util/api/likernft/fiat/index.ts
> +    .toFixed(0, BigNumber.ROUND_UP));
I extracted the modifier and used the same reducer for both cases, to guard exceptional/unwanted cases.

2023-10-03 13:37 UTC, williamchong requested changes

2023-10-03 13:37 UTC, williamchong commented on config/config.js
> +config.LIKER_NFT_LIKE_PRICE_DISCOUNT_RATIO = 0.05;
Should not hardcode LIKE discount as conflict, we should just calculate fiat price - stripe fee and use that as discounted price

2023-10-03 13:54 UTC, nwingt commented on src/util/api/likernft/fiat/index.ts
>      .reduce((acc, { price }) => acc.plus(price), new BigNumber(0));
I wonder why purchaseInfoList is `{ price }` here but `price` in above

2023-10-03 14:36 UTC, WeiJun0827 commented on src/util/api/likernft/fiat/index.ts
>      .reduce((acc, { price }) => acc.plus(price), new BigNumber(0));
Indeed, should add a `map` before calling reducer.

2023-10-04 12:26 UTC, williamchong commented on src/routes/likernft/payment.ts
> +        totalLIKEPriceNoDiscount,
How about prediscount instead of nodiscount

2023-10-04 12:26 UTC, williamchong commented on src/util/api/likernft/purchase.ts
> +    .minus(new BigNumber(LIKER_NFT_STRIPE_FEE_USD_INTERCEPT).dividedBy(nftCountOfOrder))
For consistency we should just minus the flat price for all nft?

2023-10-04 13:20 UTC, williamchong approved these changes

2023-10-05 16:05 UTC, merged