[TAS-526] ✨ Add LIKE pricing for NFT Book
likecoin/likecoin-api-public pull request #544
Opened 2023-11-01 13:52 UTC by WeiJun0827

2023-11-01 14:02 UTC, WeiJun0827 commented
Example link:
https://api.rinkeby.like.co/likernft/book/payment/price?class_id=likenft14fhmat075g4wvmxxlj8shr4mryt8czd5q493mhz99luudxglra4ql69r00&price_index=0

2023-11-17 06:36 UTC, williamchong commented on src/routes/likernft/book/index.ts
>  router.use('/book/purchase', purchase);
can the `payment` route be under `purchase` also? both seems similar in meaning

2023-11-17 06:36 UTC, williamchong commented on src/routes/likernft/book/payment.ts
> +      } = await calculatePayment([price]);
Please include gas price also

2023-11-17 06:36 UTC, williamchong commented on src/routes/likernft/book/purchase.ts
> +      const priceIndex = Number(priceIndexString);
Consider accepting `email` as input as body
And since we are accepting a body, `tx_hash` might as well be in body too

2023-11-17 06:36 UTC, williamchong commented on src/util/api/likernft/book/index.ts
> +    if (status !== 'paid' && type !== 'LIKE') {
Maybe check for an expected status also if `type === 'LIKE'`

2023-11-17 13:02 UTC, WeiJun0827 commented on src/routes/likernft/book/index.ts
>  router.use('/book/purchase', purchase);
Well, yes, sort of... we  have `GET /likernft/payment/price` to query LIKE price of W.NFT.
So the `GET /likernft/book/payment/price` is named to keep the symmetric. 
But `GET /likernft/book/:classId/price` would probably be better I think.

2023-11-17 13:17 UTC, WeiJun0827 commented on src/util/api/likernft/book/index.ts
> +    if (status !== 'paid' && type !== 'LIKE') {
Seems I shouldn't set this check, just leave it unchanged

2023-11-27 03:51 UTC, williamchong requested changes

2023-11-27 03:51 UTC, williamchong commented on src/routes/likernft/book/purchase.ts
> +      await createNewNFTBookPayment(classId, paymentId, {
I think to align with stripe payment flow, the order should be `createNewNFTBookPayment()` => `execAuthz()` => `processNFTBookPurchase()`, since new payment is created before actual payment.
In this case we can also just use ```const paymentId = uuidv4();
      const claimToken = crypto.randomBytes(32).toString('hex');``` instead of hash

2023-11-27 04:36 UTC, WeiJun0827 commented on src/routes/likernft/book/purchase.ts
> +      await createNewNFTBookPayment(classId, paymentId, {
Should we store `execTxHash` somewhere?

2023-11-27 06:52 UTC, williamchong commented on src/routes/likernft/book/purchase.ts
> +      await createNewNFTBookPayment(classId, paymentId, {
Yes store it inside the payment object

2023-11-27 06:56 UTC, williamchong requested changes

2023-11-27 06:56 UTC, williamchong commented on src/routes/likernft/book/purchase.ts
> +        txHash: grantTxHash,
Should handle `from` parameter because we need this for calculating commission of channels

Ref: https://github.com/likecoin/likecoin-api-public/blob/master/src/routes/likernft/book/purchase.ts#L73

2023-11-27 06:56 UTC, williamchong commented on src/routes/likernft/book/purchase.ts
> +      const execTxHash = await execAuthz(granterWallet, ownerWallet, LIKEPrice);
Actually if `from` === `liker_land`, we would want to get 30%. 
Also we collect 5% for commission for all purchase, no matter channel.
Ref: https://github.com/likecoin/likecoin-api-public/blob/master/src/routes/likernft/book/purchase.ts#L148

2023-11-27 08:07 UTC, WeiJun0827 commented on src/routes/likernft/book/purchase.ts
> +      await createNewNFTBookPayment(classId, paymentId, {
Updated, tho still wondering if `claimToken` is meaningful here?

2023-11-27 14:11 UTC, williamchong commented on src/routes/likernft/book/purchase.ts
> +      await createNewNFTBookPayment(classId, paymentId, {
No unless we want to "resend" a link in the future, which might happen for gift feature (not sure yet)

2023-12-01 08:15 UTC, williamchong requested changes

2023-12-01 08:15 UTC, williamchong commented on src/util/api/likernft/book/index.ts
> +    .toFixed();
Fee and commission needs to be sent to `LIKER_NFT_FEE_ADDRESS` instead of `LIKER_NFT_TARGET_ADDRESS`

2023-12-03 16:29 UTC, williamchong approved these changes

2023-12-03 16:30 UTC, merged