🔧 Set `moduleResolution` to `node16`
likecoin/likecoin-api-public pull request #580
Opened 2023-12-19 10:38 UTC by WeiJun0827

Prerequisite config of using w3up client

2023-12-21 09:45 UTC, WeiJun0827 commented
Demo video

https://github.com/likecoin/likecoin-api-public/assets/33746295/bc19f3d7-f41d-4041-9c1f-0e9e28430d47

2023-12-21 15:28 UTC, williamchong requested changes

2023-12-21 15:28 UTC, williamchong commented on src/util/arweave/index.ts
> +    global.crypto = require('crypto'); // hack for bundlr
```suggestion
    if (!global.crypto) global.crypto = require('crypto'); // hack for bundlr
```

2023-12-21 15:28 UTC, williamchong commented on src/util/arweave/signer.ts
> +    global.crypto = require('crypto'); // hack for bundlr
```suggestion
    if (!global.crypto) global.crypto = require('crypto'); // hack for bundlr
```

2023-12-27 19:52 UTC, williamchong approved these changes

2023-12-29 03:24 UTC, merged