[TAS-881] ✨ Support auto deliver NFT Book
likecoin/likecoin-api-public pull request #596
Opened 2024-01-12 08:23 UTC by WeiJun0827

2024-01-18 15:01 UTC, williamchong requested changes

2024-01-18 15:01 UTC, williamchong commented on src/util/api/likernft/book/purchase.ts
> +  }
Please allocate this nftId on `claim`, `new` payment can be spamed without any cost

2024-01-19 07:34 UTC, WeiJun0827 commented on src/util/api/likernft/book/purchase.ts
> +  }
Is it OK to allocate when users finish payment? Since it updates stock in the same transaction too.

2024-01-19 08:26 UTC, williamchong requested changes

2024-01-19 08:26 UTC, williamchong commented on src/routes/likernft/book/purchase.ts
> +        updateNFTBookPostDeliveryData({
Do we need to await here?

2024-01-19 08:26 UTC, williamchong commented on src/util/api/likernft/book/purchase.ts
> +        if (status === 'sendingNFT') {
Where do we set `sendingNFT` now?

2024-01-19 08:26 UTC, williamchong commented on src/util/api/likernft/book/purchase.ts
> +            pendingNFTCount: FieldValue.increment(-1),
Where do we set `pendingNFTCount-1` after nft is delivered?
Actually do we need `pendingNFTCount+1` for auto deliver?

2024-01-19 08:26 UTC, williamchong commented on src/util/api/likernft/book/purchase.ts
> +      logType: 'BookNFTSentUpdate',
Please add  a field stating this is auto delivered

2024-01-19 08:32 UTC, WeiJun0827 commented on src/routes/likernft/book/purchase.ts
> +        updateNFTBookPostDeliveryData({
To retrieve `email, isGift, giftInfo` for upcoming processes?

2024-01-22 03:43 UTC, merged