🚸 Sending book sales email by default
likecoin/likecoin-api-public pull request #657
Opened 2024-04-02 08:37 UTC by AuroraHuang22

2024-04-07 11:12 UTC, williamchong requested changes

2024-04-07 11:12 UTC, williamchong commented on src/util/api/likernft/book/purchase.ts
> +  if (notificationEmails) {
if we don't have `notificationEmails` we should pass `notificationEmails = []`
Also do we know if aws ses accept 
```Destination: {
      ToAddresses: [],
      BccAddresses...
    },
```
as valie input?

2024-04-08 01:40 UTC, AuroraHuang22 commented on src/util/api/likernft/book/purchase.ts
> +  if (notificationEmails) {
Since the Toaddresses is [not required](https://docs.aws.amazon.com/ses/latest/APIReference/API_Destination.html) for ses:

[🎨 Handle empty toAddress for ses](https://github.com/likecoin/likecoin-api-public/pull/657/commits/bcdc39caed215cd72bb8fc2f7fe11ffe48eba5f6)

2024-04-08 10:09 UTC, williamchong approved these changes

2024-04-08 10:10 UTC, merged