[TAS-1522] ✨ Add Airtable record for each sales
likecoin/likecoin-api-public pull request #669
Opened 2024-04-16 16:48 UTC by nwingt

2024-04-17 06:01 UTC, williamchong requested changes

2024-04-17 06:01 UTC, williamchong commented on src/util/airtable.ts
> +  if (pi.latest_charge && typeof pi.latest_charge !== 'string') {
Should we fetch object from stripe if this is string?

2024-04-17 06:01 UTC, williamchong commented on src/util/airtable.ts
> +    if (balanceTx && typeof balanceTx !== 'string') {
Should we fetch object from stripe if this is string?

2024-04-17 06:01 UTC, williamchong commented on src/util/airtable.ts
> +            stripeFeeCurrency = currency;
Should use .find instead?

2024-04-17 07:30 UTC, nwingt commented on src/util/airtable.ts
> +    if (balanceTx && typeof balanceTx !== 'string') {
It shouldn't be a string as we added `expand` param in [here](https://github.com/likecoin/likecoin-api-public/blob/6e769f6a83ddf71a86df1fcc6410bf2330bcbcba/src/util/api/likernft/book/collection/purchase.ts#L461-L462)

2024-04-17 07:38 UTC, nwingt commented on src/util/airtable.ts
> +            stripeFeeCurrency = currency;
Updated

2024-04-17 08:35 UTC, williamchong commented on src/util/airtable.ts
> +    if (balanceTx && typeof balanceTx !== 'string') {
Add a console error if we encounter string? Someone might misuse this function without knowing

2024-04-18 08:01 UTC, williamchong approved these changes

2024-04-18 08:01 UTC, merged