[TAS-1618] 🐛 Calculate application fee with exchange rate
likecoin/likecoin-api-public pull request #679
Opened 2024-05-06 09:17 UTC by nwingt

2024-05-06 15:10 UTC, williamchong requested changes

2024-05-06 15:10 UTC, williamchong commented on src/util/airtable.ts
>      : balanceTxAmount * NFT_BOOK_LIKER_LAND_FEE_RATIO;
I think not only `applicationFee`, but `likerLandCommission`, `likerLandArtFee`, `likerLandTipFee`, all data that come from `pi` or `metadata` without explicit currency stated should all be converted

2024-05-07 05:57 UTC, nwingt commented on src/util/airtable.ts
>      : balanceTxAmount * NFT_BOOK_LIKER_LAND_FEE_RATIO;
Seem Stripe fee currency is always USD, but I guard it anyway

2024-05-07 09:03 UTC, williamchong requested changes

2024-05-07 09:03 UTC, williamchong commented on src/util/api/likernft/book/collection/purchase.ts
> +      stripe.paymentIntents.capture(paymentIntent as string, { expand: ['latest_charge.balance_transaction', 'latest_charge.application_fee'] }),
You might also want to edit the one in `src/util/api/likernft/book/purchase.ts`

2024-05-07 09:09 UTC, nwingt commented on src/util/api/likernft/book/collection/purchase.ts
> +      stripe.paymentIntents.capture(paymentIntent as string, { expand: ['latest_charge.balance_transaction', 'latest_charge.application_fee'] }),
Updated

2024-05-07 09:49 UTC, williamchong approved these changes
`balanceTxExchangeRate` could be `1` instead of `undefined`? Not sure which default value is best

2024-05-07 10:10 UTC, nwingt commented
If the default is set to 1, then it still multiplies by 1, which I think is not necessary

2024-05-07 13:51 UTC, merged