✨ Send slack message for NFT Book invalid id
likecoin/likecoin-api-public pull request #744
Opened 2024-09-05 16:39 UTC by AuroraHuang22

Expected workflow
<img width="395" alt="截圖 2024-09-06 凌晨12 38 13" src="https://github.com/user-attachments/assets/dfbe911d-9961-4f8c-a8f4-66fa60f6923b">

2024-09-05 18:14 UTC, williamchong requested changes

2024-09-05 18:14 UTC, williamchong commented on config/config.js
> +config.NFT_BOOK_SALES_INVALID_ID_NOTIFICATION_WEBHOOK = '';
```suggestion
config.NFT_BOOK_SALES_INVALID_CHANNEL_ID_NOTIFICATION_WEBHOOK = '';
```

2024-09-05 18:14 UTC, williamchong commented on src/util/slack.ts
> +export async function sendNFTBookInvalidIdSlackNotification({
```suggestion
export async function sendNFTBookInvalidChannelIdSlackNotification({
```

2024-09-05 18:14 UTC, williamchong commented on src/util/slack.ts
> +      : getNFTBookStoreSendPageURL(classId, paymentId);
What is the use of giving book press link here?

2024-09-05 18:14 UTC, williamchong commented on src/util/slack.ts
> +      isStripeConnected,
Instead of just true or false, I think we might want to know different error cases
- channel id not start with `@` and not exists in db as legacy string
- start with `@` but not valid liker id
- we can find valid liker id, but stripe connect does not exists
- stripe connect account exists, but is not ready (setup not complete)

2024-09-05 18:14 UTC, williamchong commented on src/util/api/likernft/book/purchase.ts
> +        await sendNFTBookInvalidIdSlackNotification({
Do we know these information in `handleStripeConnectedAccount`? Should we handle this there or use a return value/error from that function?

2024-09-05 18:14 UTC, williamchong commented on src/util/api/likernft/book/collection/purchase.ts
> +      if (!bookUserInfo || !bookUserInfo.isStripeConnectReady) {
Do we know these information in `handleStripeConnectedAccount`? Should we handle this there or use a return value/error from that function?

2024-09-07 07:06 UTC, AuroraHuang22 commented on config/config.js
> +config.NFT_BOOK_SALES_INVALID_ID_NOTIFICATION_WEBHOOK = '';
[🎨 Rename config & function name](https://github.com/likecoin/likecoin-api-public/pull/744/commits/3baf5dcd3bf3d806993441857863b4923861322a)

2024-09-07 07:06 UTC, AuroraHuang22 commented on src/util/slack.ts
> +export async function sendNFTBookInvalidIdSlackNotification({
[🎨 Rename config & function name](https://github.com/likecoin/likecoin-api-public/pull/744/commits/3baf5dcd3bf3d806993441857863b4923861322a)

2024-09-07 07:06 UTC, AuroraHuang22 commented on src/util/slack.ts
> +      : getNFTBookStoreSendPageURL(classId, paymentId);
[🔥 Remove paymentId](https://github.com/likecoin/likecoin-api-public/pull/744/commits/eefee7dd5bb8023c1bca2127cc61f56c21c313cf)

2024-09-07 07:06 UTC, AuroraHuang22 commented on src/util/slack.ts
> +      isStripeConnected,
[♻️ Move sending logic to handleStripeConnectedAccount](https://github.com/likecoin/likecoin-api-public/pull/744/commits/e59d85e74038130c0c1222246c6f003eced5bc14)

2024-09-07 07:06 UTC, AuroraHuang22 commented on src/util/api/likernft/book/purchase.ts
> +        await sendNFTBookInvalidIdSlackNotification({
[♻️ Move sending logic to handleStripeConnectedAccount](https://github.com/likecoin/likecoin-api-public/pull/744/commits/e59d85e74038130c0c1222246c6f003eced5bc14)

2024-09-07 07:06 UTC, AuroraHuang22 commented on src/util/api/likernft/book/collection/purchase.ts
> +      if (!bookUserInfo || !bookUserInfo.isStripeConnectReady) {
[♻️ Move sending logic to handleStripeConnectedAccount](https://github.com/likecoin/likecoin-api-public/pull/744/commits/e59d85e74038130c0c1222246c6f003eced5bc14)

2024-09-08 18:18 UTC, williamchong requested changes

2024-09-08 18:18 UTC, williamchong commented on src/util/api/likernft/book/purchase.ts
> +    let isInvalidChannelId = false;
Seems default this to `true` then set it back according to the result of `fromUser` would make the logic simpler

2024-09-08 18:18 UTC, williamchong commented on src/util/api/likernft/book/purchase.ts
> +    if (isInvalidChannelId) {
Is this just the `else` case for `(fromUser && fromUser.bookUserInfo)` ?

2024-09-08 18:18 UTC, williamchong commented on src/util/api/likernft/book/cart.ts
> +import { getBookUserInfoFromLikerId, getBookUserInfoFromLegacyString } from './user';
Please reset if not used

2024-09-08 18:18 UTC, williamchong commented on src/util/api/likernft/book/collection/purchase.ts
> +import { getBookUserInfoFromLikerId, getBookUserInfoFromLegacyString } from '../user';
Please reset if not used

2024-09-08 18:18 UTC, williamchong commented on src/util/api/likernft/book/purchase.ts
> +      }
Should merge with below cases for `if (isStripeConnectReady)` and `if (fromStripeConnectAccountId)` etc with `if (else if) else`

2024-09-09 04:47 UTC, AuroraHuang22 commented on src/util/api/likernft/book/collection/purchase.ts
> +import { getBookUserInfoFromLikerId, getBookUserInfoFromLegacyString } from '../user';
[🔥 Remove unused import](https://github.com/likecoin/likecoin-api-public/pull/744/commits/e0603c9eb527d078fdac4879e0368697b99e5211)

2024-09-09 04:47 UTC, AuroraHuang22 commented on src/util/api/likernft/book/cart.ts
> +import { getBookUserInfoFromLikerId, getBookUserInfoFromLegacyString } from './user';
[🔥 Remove unused import](https://github.com/likecoin/likecoin-api-public/pull/744/commits/e0603c9eb527d078fdac4879e0368697b99e5211)

2024-09-09 04:47 UTC, AuroraHuang22 commented on src/util/api/likernft/book/purchase.ts
> +    let isInvalidChannelId = false;
[♻️ Simplify checking logic for isInvalidChannelId](https://github.com/likecoin/likecoin-api-public/pull/744/commits/2e667f51bb1db0eafb981b8bdcd6b94aebe852d5)

2024-09-09 04:48 UTC, AuroraHuang22 commented on src/util/api/likernft/book/purchase.ts
> +    if (isInvalidChannelId) {
[♻️ Simplify checking logic for isInvalidChannelId](https://github.com/likecoin/likecoin-api-public/pull/744/commits/2e667f51bb1db0eafb981b8bdcd6b94aebe852d5)

2024-09-09 04:48 UTC, AuroraHuang22 commented on src/util/api/likernft/book/purchase.ts
> +      }
[♻️ Simplify checking logic for Stripe connection status](https://github.com/likecoin/likecoin-api-public/pull/744/commits/0fa5c37be087bdd1f88492a1fc6593a25fea3ddc)

2024-09-09 05:31 UTC, williamchong approved these changes

2024-09-09 06:20 UTC, merged