[TAS-2147] ✨ Search for book payment status
likecoin/likecoin-api-public pull request #802
Opened 2024-10-23 14:13 UTC by AuroraHuang22

- [ ] `/payment txs ${email/wallet} ${(classId/status)--optional}` Find all transactions related to the provided info
- [ ] 🚧 `/payment status ${classId+payment/cartId}` Check the status of a specific payment

2024-10-25 08:51 UTC, williamchong requested changes

2024-10-25 08:51 UTC, williamchong commented on src/util/slack.ts
> +}
Just call `toDate()`

https://firebase.google.com/docs/reference/js/v8/firebase.firestore.Timestamp#todate

2024-10-25 08:51 UTC, williamchong commented on src/routes/slack/payment.ts
> +      classId = statusOrClassId;
Please also support collection id

2024-10-25 08:51 UTC, williamchong commented on src/routes/slack/payment.ts
> +        .where(queryType, '==', emailOrWallet)
Please also add limit for this query just in case

2024-10-25 08:51 UTC, williamchong commented on src/routes/slack/payment.ts
> +// eslint-disable-next-line consistent-return
Please try to write consistent return value instead of disabling lint rule
In which line we can't have consistent return?

2024-10-25 08:51 UTC, williamchong commented on src/routes/slack/payment.ts
> +// eslint-disable-next-line consistent-return
Please try to write consistent return value instead of disabling lint rule
In which line we can't have consistent return?

2024-10-25 08:51 UTC, williamchong commented on src/routes/slack/payment.ts
> +          return await handleStatusQuery(params, res);
It would make the code simpler if these 2 query just handle the parsing of params, then we can handle the actual firestore query and formatting with a same function

2024-10-30 04:37 UTC, nwingt reviewed
Can we use [Block Kit](https://app.slack.com/block-kit-builder/T7B3ZCQUE#%7B%22blocks%22:%5B%7B%22type%22:%22header%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Transactions%20for%20williamchong@like.co%20in%20cart%20collection%22%7D%7D,%7B%22type%22:%22divider%22%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22%F0%9F%92%B3%20*Payment%20Record%20%231*%5Cn%5Cn*Payment%20ID*%5Cn%3Chttps://dashboard.stripe.com/test/search?query=478d8619-bdb1-446f-aadf-f26240430476%7C478d8619-bdb1-446f-aadf-f26240430476%3E%5Cn%5Cn*Class%20ID*%5Cn%3Chttps://liker.land/nft/class/likenft10e4gsezx2xfujwkl89eOvv07j8x3ha4hreulc77p4wm4manag4rqk6zeq8%7Clikenft10e4gsezx2xfujwkl89eOvv07j8x3ha4hreulc77p4wm4manag4rqk6zeq8%3E%5Cn%5Cn*Session%20ID*%5Cn%60cs_test_b1MP2Nj4pYKhAiRTkPTB7COlAgzQVecLg9nZThGcS2rxxYFMAE7cmEiK2T%60%5Cn%5Cn*Claim%20Token*%5Cn%604b95baf378a4256272190eab21fb7594d09a150bd042780c1c170bd81490773f%60%22%7D,%22fields%22:%5B%7B%22type%22:%22mrkdwn%22,%22text%22:%22*Timestamp*%5Cn10/14/2024%2010:34:37AM%22%7D,%7B%22type%22:%22mrkdwn%22,%22text%22:%22*Email*%5Cnwilliamchong@like.co%22%7D,%7B%22type%22:%22mrkdwn%22,%22text%22:%22*Price*%5Cn1000%22%7D,%7B%22type%22:%22mrkdwn%22,%22text%22:%22*Status*%5Cnpaid%22%7D,%7B%22type%22:%22mrkdwn%22,%22text%22:%22*Channel*%5Cn%60liker_land%60%22%7D%5D%7D,%7B%22type%22:%22divider%22%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22%F0%9F%92%B3%20*Payment%20Record%20%232*%5Cn%5Cn*Payment%20ID*%5Cn%3Chttps://dashboard.stripe.com/test/search?query=478d8619-bdb1-446f-aadf-f26240430476%7C478d8619-bdb1-446f-aadf-f26240430476%3E%5Cn%5Cn*Class%20ID*%5Cn%3Chttps://liker.land/nft/class/likenft10e4gsezx2xfujwkl89eOvv07j8x3ha4hreulc77p4wm4manag4rqk6zeq8%7Clikenft10e4gsezx2xfujwkl89eOvv07j8x3ha4hreulc77p4wm4manag4rqk6zeq8%3E%5Cn%5Cn*Session%20ID*%5Cn%60cs_test_b1MP2Nj4pYKhAiRTkPTB7COlAgzQVecLg9nZThGcS2rxxYFMAE7cmEiK2T%60%5Cn%5Cn*Claim%20Token*%5Cn%604b95baf378a4256272190eab21fb7594d09a150bd042780c1c170bd81490773f%60%22%7D,%22fields%22:%5B%7B%22type%22:%22mrkdwn%22,%22text%22:%22*Timestamp*%5Cn10/14/2024%2010:34:37AM%22%7D,%7B%22type%22:%22mrkdwn%22,%22text%22:%22*Email*%5Cnwilliamchong@like.co%22%7D,%7B%22type%22:%22mrkdwn%22,%22text%22:%22*Price*%5Cn1000%22%7D,%7B%22type%22:%22mrkdwn%22,%22text%22:%22*Status*%5Cnpaid%22%7D,%7B%22type%22:%22mrkdwn%22,%22text%22:%22*Channel*%5Cn%60liker_land%60%22%7D%5D%7D%5D%7D) for the response message?

![image](https://github.com/user-attachments/assets/90f2bfa7-c316-4605-9354-8fcd431bb20e)

2024-10-31 08:36 UTC, AuroraHuang22 commented on src/routes/slack/payment.ts
> +        .where(queryType, '==', emailOrWallet)
[🎨 Add limit to txs query by classId](https://github.com/likecoin/likecoin-api-public/pull/802/commits/45adc50fad14e9c7c66ae8a754a127e36c4a3405)

2024-10-31 08:37 UTC, AuroraHuang22 commented on src/routes/slack/payment.ts
> +          return await handleStatusQuery(params, res);
[♻️ Simplify txs query function](https://github.com/likecoin/likecoin-api-public/pull/802/commits/2e190c8aeda7d4ec7845944c8977ad145e0f3869)

2024-10-31 08:37 UTC, AuroraHuang22 commented
> Can we use [Block Kit](https://app.slack.com/block-kit-builder/T7B3ZCQUE#%7B%22blocks%22:%5B%7B%22type%22:%22header%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Transactions%20for%20williamchong@like.co%20in%20cart%20collection%22%7D%7D,%7B%22type%22:%22divider%22%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22%F0%9F%92%B3%20*Payment%20Record%20%231*%5Cn%5Cn*Payment%20ID*%5Cn%3Chttps://dashboard.stripe.com/test/search?query=478d8619-bdb1-446f-aadf-f26240430476%7C478d8619-bdb1-446f-aadf-f26240430476%3E%5Cn%5Cn*Class%20ID*%5Cn%3Chttps://liker.land/nft/class/likenft10e4gsezx2xfujwkl89eOvv07j8x3ha4hreulc77p4wm4manag4rqk6zeq8%7Clikenft10e4gsezx2xfujwkl89eOvv07j8x3ha4hreulc77p4wm4manag4rqk6zeq8%3E%5Cn%5Cn*Session%20ID*%5Cn%60cs_test_b1MP2Nj4pYKhAiRTkPTB7COlAgzQVecLg9nZThGcS2rxxYFMAE7cmEiK2T%60%5Cn%5Cn*Claim%20Token*%5Cn%604b95baf378a4256272190eab21fb7594d09a150bd042780c1c170bd81490773f%60%22%7D,%22fields%22:%5B%7B%22type%22:%22mrkdwn%22,%22text%22:%22*Timestamp*%5Cn10/14/2024%2010:34:37AM%22%7D,%7B%22type%22:%22mrkdwn%22,%22text%22:%22*Email*%5Cnwilliamchong@like.co%22%7D,%7B%22type%22:%22mrkdwn%22,%22text%22:%22*Price*%5Cn1000%22%7D,%7B%22type%22:%22mrkdwn%22,%22text%22:%22*Status*%5Cnpaid%22%7D,%7B%22type%22:%22mrkdwn%22,%22text%22:%22*Channel*%5Cn%60liker_land%60%22%7D%5D%7D,%7B%22type%22:%22divider%22%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22%F0%9F%92%B3%20*Payment%20Record%20%232*%5Cn%5Cn*Payment%20ID*%5Cn%3Chttps://dashboard.stripe.com/test/search?query=478d8619-bdb1-446f-aadf-f26240430476%7C478d8619-bdb1-446f-aadf-f26240430476%3E%5Cn%5Cn*Class%20ID*%5Cn%3Chttps://liker.land/nft/class/likenft10e4gsezx2xfujwkl89eOvv07j8x3ha4hreulc77p4wm4manag4rqk6zeq8%7Clikenft10e4gsezx2xfujwkl89eOvv07j8x3ha4hreulc77p4wm4manag4rqk6zeq8%3E%5Cn%5Cn*Session%20ID*%5Cn%60cs_test_b1MP2Nj4pYKhAiRTkPTB7COlAgzQVecLg9nZThGcS2rxxYFMAE7cmEiK2T%60%5Cn%5Cn*Claim%20Token*%5Cn%604b95baf378a4256272190eab21fb7594d09a150bd042780c1c170bd81490773f%60%22%7D,%22fields%22:%5B%7B%22type%22:%22mrkdwn%22,%22text%22:%22*Timestamp*%5Cn10/14/2024%2010:34:37AM%22%7D,%7B%22type%22:%22mrkdwn%22,%22text%22:%22*Email*%5Cnwilliamchong@like.co%22%7D,%7B%22type%22:%22mrkdwn%22,%22text%22:%22*Price*%5Cn1000%22%7D,%7B%22type%22:%22mrkdwn%22,%22text%22:%22*Status*%5Cnpaid%22%7D,%7B%22type%22:%22mrkdwn%22,%22text%22:%22*Channel*%5Cn%60liker_land%60%22%7D%5D%7D%5D%7D) for the response message?
> 
> ![image](https://private-user-images.githubusercontent.com/17264716/381392778-90f2bfa7-c316-4605-9354-8fcd431bb20e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNjQwNjQsIm5iZiI6MTczMDM2Mzc2NCwicGF0aCI6Ii8xNzI2NDcxNi8zODEzOTI3NzgtOTBmMmJmYTctYzMxNi00NjA1LTkzNTQtOGZjZDQzMWJiMjBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDA4MzYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkZWI5YmY5OTE5NDA5OTdmM2Y1MDNjOWU2ZTIzMDA1ZmU4ZmU0OTZjZjc0NDMwZGYyOWVhNWJjOTIzYTZjNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5dZimaE57eZIaRNV3SaoUutULZAXuhtnIzEVKGz9s34)

[🎨 Reformat response data with Block Kit](https://github.com/likecoin/likecoin-api-public/pull/802/commits/043374827a2a127c26b3c3d8ea62fd492a2c8d94)

2024-10-31 17:56 UTC, williamchong requested changes

2024-10-31 17:56 UTC, williamchong commented on src/routes/slack/payment.ts
> +      const emailOrWallet = email || wallet;
seems better to judge `emailOrWallet` with `queryType`

2024-10-31 17:56 UTC, williamchong commented on src/routes/slack/payment.ts
> +      }
Maybe it is better to just return `blocks` in each `if else`, then call `res.json` at the very end of this function

2024-11-04 18:02 UTC, williamchong commented on src/util/slack.ts
> +  const docsArray = Array.isArray(transactionDocs) ? transactionDocs : [transactionDocs];
It seems strange that we want to overload this function like this
Just force `transactionDocs` as array, and if we have singular param we warp it as `[doc]` when calling

2024-11-04 18:02 UTC, williamchong commented on src/routes/slack/payment.ts
> +        });
Would it be possible that we just return `transactions` (or `[transactionDoc]` for singular case` for each `if` block, then we would call
```
        const formattedTransactions = mapTransactionDocsToSlackSections(transactions);
        blocks = createPaymentSlackBlocks({
          transactions: formattedTransactions, 
          emailOrWallet , classId, collectionId, status, cartId, paymentId,
        });
```
Altogether at the end for `if (transactions.length > 0)` ? We dont need to conditionally pass params into `createPaymentSlackBlocks`, it has default values

2024-11-06 18:31 UTC, williamchong approved these changes

2024-11-07 08:10 UTC, merged