✨ Add LikeCoin price api
likecoin/likecoin-api-public pull request #87
Opened 2019-11-01 05:15 UTC by mckingho

2019-11-01 05:17 UTC, williamchong requested changes

2019-11-01 05:17 UTC, williamchong007 commented on src/routes/misc/price.js
> +        .then(r => parseFloat(r.data[0].price_usd))
plz support currency override via querystring (usd as default if not set)

2019-11-01 08:28 UTC, williamchong requested changes

2019-11-01 08:28 UTC, williamchong007 commented on src/routes/misc/price.js
> +  const { convert = 'usd' } = req.query;
`currency` should be a better name

2019-11-01 09:45 UTC, nnkken approved these changes

2019-11-01 12:42 UTC, mckingho commented on src/routes/misc/price.js
> +  res.send({ price });
@nnkken Should I return `price:null` or `status 500` for error case?

2019-11-05 09:35 UTC, nnkken approved these changes

2019-11-05 10:52 UTC, williamchong requested changes

2019-11-05 10:52 UTC, williamchong007 commented on src/routes/misc/price.js
> +      price = Math.max(...prices.filter(p => p !== undefined));
instead of checking undefined,  check for `isNaN`.
Since we need to iterate the array in both line 32 and 36 anyway, we can just filter the array by `isNaN` in line 32, and use the resulting array's length for the `if` clause. The result array can be directly use in line 36.

2019-11-06 09:06 UTC, merged